<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;

class RestoreOriginalHotelsSeeder extends Seeder
{
    public function run(): void
    {
        $originalHotels = [
            'فندق ريتز كارلتون موسكو' => ['title' => 'The Ritz-Carlton Moscow', 'address' => 'Tverskaya Street 3, Moscow'],
            'فندق فور سيزونز موسكو' => ['title' => 'Four Seasons Hotel Moscow', 'address' => 'Okhotny Ryad 2, Moscow'],
            'فندق متروبول موسكو' => ['title' => 'Hotel Metropol Moscow', 'address' => 'Teatralny Proezd 2, Moscow'],
            'فندق أرارات بارك حياة موسكو' => ['title' => 'Ararat Park Hyatt Moscow', 'address' => 'Neglinnaya Street 4, Moscow'],
            'فندق سانت ريجيس موسكو' => ['title' => 'The St. Regis Moscow', 'address' => 'Nikolskaya Street 12, Moscow'],
            'فندق لوته موسكو' => ['title' => 'Lotte Hotel Moscow', 'address' => 'Novinskiy Boulevard 8, Moscow'],
            'فندق راديسون كوليكشن موسكو' => ['title' => 'Radisson Collection Hotel Moscow', 'address' => 'Kutuzovsky Prospekt 2/1, Moscow'],
            'فندق سويس أوتيل كراسني خولمي موسكو' => ['title' => 'Swissotel Krasnye Holmy Moscow', 'address' => 'Kosmodamianskaya Naberezhnaya 52, Moscow'],
            'فندق ناشيونال موسكو' => ['title' => 'Hotel National Moscow', 'address' => 'Mokhovaya Street 15/1, Moscow'],
            'فندق بالتشوغ كيمبينسكي موسكو' => ['title' => 'Baltschug Kempinski Moscow', 'address' => 'Balchug Street 1, Moscow'],

            'فندق كونتيننتال أوسلو' => ['title' => 'Hotel Continental Oslo', 'address' => 'Stortingsgata 24/26, Oslo'],
            'فندق ذا ثيف أوسلو' => ['title' => 'The Thief Oslo', 'address' => 'Landgangen 1, Oslo'],
            'فندق غراند أوسلو' => ['title' => 'Grand Hotel Oslo', 'address' => 'Karl Johans gate 31, Oslo'],
            'فندق راديسون بلو بلازا أوسلو' => ['title' => 'Radisson Blu Plaza Hotel Oslo', 'address' => 'Sonja Henies plass 3, Oslo'],
            'فندق كلاريون ذا هاب' => ['title' => 'Clarion Hotel The Hub', 'address' => 'Biskop Gunnerus gate 3, Oslo'],
            'فندق سكانديك هولمنكولن بارك' => ['title' => 'Scandic Holmenkollen Park', 'address' => 'Kongeveien 26, Oslo'],
            'فندق بريستول أوسلو' => ['title' => 'Hotel Bristol Oslo', 'address' => 'Kristian IVs gate 7, Oslo'],
            'فندق أمريكالينين أوسلو' => ['title' => 'Amerikalinjen Oslo', 'address' => 'Jernbanetorget 2, Oslo'],
            'فندق سكانديك فولكان' => ['title' => 'Scandic Vulkan', 'address' => 'Vulkan 13B, Oslo'],
            'فيلا فروغنر' => ['title' => 'Villa Frogner', 'address' => 'Nordahl Bruns gate 26, Oslo'],

            'فندق بلازا نيويورك' => ['title' => 'The Plaza New York', 'address' => '768 5th Ave, New York, NY'],
            'فندق سانت ريجيس نيويورك' => ['title' => 'The St. Regis New York', 'address' => '2 E 55th St, New York, NY'],
            'فندق كارلايل نيويورك' => ['title' => 'The Carlyle New York', 'address' => '35 E 76th St, New York, NY'],
            'فندق بيير نيويورك' => ['title' => 'The Pierre New York', 'address' => '2 E 61st St, New York, NY'],
            'فندق ريتز كارلتون نيويورك' => ['title' => 'The Ritz-Carlton New York', 'address' => '50 Central Park S, New York, NY'],
            'فندق فور سيزونز نيويورك' => ['title' => 'Four Seasons Hotel New York', 'address' => '57th St, New York, NY'],
            'فندق ذا مارك نيويورك' => ['title' => 'The Mark New York', 'address' => '25 E 77th St, New York, NY'],
            'فندق لويل نيويورك' => ['title' => 'The Lowell New York', 'address' => '28 E 63rd St, New York, NY'],
            'فندق شيري نيذرلاند' => ['title' => 'The Sherry-Netherland', 'address' => '781 5th Ave, New York, NY'],
            'فندق غرينتش' => ['title' => 'The Greenwich Hotel', 'address' => '377 Greenwich St, New York, NY'],

            'فندق ريتز باريس' => ['title' => 'The Ritz Paris', 'address' => '15 Place Vendôme, Paris'],
            'فندق فور سيزونز جورج الخامس' => ['title' => 'Four Seasons Hotel George V', 'address' => '31 Avenue George V, Paris'],
            'فندق لو بريستول باريس' => ['title' => 'Le Bristol Paris', 'address' => '112 Rue du Faubourg Saint-Honoré, Paris'],
            'فندق بلازا أثينيه' => ['title' => 'Hotel Plaza Athénée', 'address' => '25 Avenue Montaigne, Paris'],
            'فندق لو موريس' => ['title' => 'Le Meurice', 'address' => '228 Rue de Rivoli, Paris'],
            'فندق شانغريلا باريس' => ['title' => 'Shangri-La Hotel Paris', 'address' => '10 Avenue d\'Iéna, Paris'],
            'فندق بارك حياة باريس فاندوم' => ['title' => 'Park Hyatt Paris-Vendôme', 'address' => '5 Rue de la Paix, Paris'],
            'فندق دو كريون' => ['title' => 'Hotel de Crillon', 'address' => '10 Place de la Concorde, Paris'],
            'فندق لا ريزيرف باريس' => ['title' => 'La Réserve Paris', 'address' => '42 Avenue Gabriel, Paris'],
            'فندق لوتيتيا' => ['title' => 'Hotel Lutetia', 'address' => '45 Boulevard Raspail, Paris'],

            'فندق أدلون كيمبينسكي برلين' => ['title' => 'Hotel Adlon Kempinski Berlin', 'address' => 'Unter den Linden 77, Berlin'],
            'فندق ريتز كارلتون برلين' => ['title' => 'The Ritz-Carlton Berlin', 'address' => 'Potsdamer Platz 3, Berlin'],
            'فندق ريجنت برلين' => ['title' => 'Regent Berlin', 'address' => 'Charlottenstraße 49, Berlin'],
            'فندق دو روم برلين' => ['title' => 'Hotel de Rome Berlin', 'address' => 'Behrenstraße 37, Berlin'],
            'فندق داس ستو برلين' => ['title' => 'Das Stue Berlin', 'address' => 'Drakestraße 1, Berlin'],
            'فندق سوهو هاوس برلين' => ['title' => 'Soho House Berlin', 'address' => 'Torstraße 1, Berlin'],
            'فندق غراند حياة برلين' => ['title' => 'Grand Hyatt Berlin', 'address' => 'Marlene-Dietrich-Platz 2, Berlin'],
            'فندق براندنبورغر هوف' => ['title' => 'Hotel Brandenburger Hof', 'address' => 'Eislebener Straße 14, Berlin'],
            'فندق أورانيا برلين' => ['title' => 'Orania Berlin', 'address' => 'Oranienstraße 40, Berlin'],
            'فندق تيتانيك جندارمنماركت برلين' => ['title' => 'Titanic Gendarmenmarkt Berlin', 'address' => 'Französische Straße 30, Berlin'],

            'فندق دو روسي روما' => ['title' => 'Hotel de Russie Rome', 'address' => 'Via del Babuino 9, Rome'],
            'فندق سانت ريجيس روما' => ['title' => 'The St. Regis Rome', 'address' => 'Via Vittorio Emanuele Orlando 3, Rome'],
            'فندق سبليندو بورتوفينو' => ['title' => 'Hotel Splendido Portofino', 'address' => 'Salita Baratta 16, Portofino'],
            'قصر غريتي البندقية' => ['title' => 'Gritti Palace Venice', 'address' => 'Campo Santa Maria del Giglio 2467, Venice'],
            'فيلا سان مارتينو مارتينا فرانكا' => ['title' => 'Villa San Martino Martina Franca', 'address' => 'Via Taranto 59, Martina Franca'],
            'فندق فور سيزونز ميلانو' => ['title' => 'Four Seasons Hotel Milano', 'address' => 'Via Gesù 6/8, Milan'],
            'فندق فيلا تشيمبروني رافيلو' => ['title' => 'Hotel Villa Cimbrone Ravello', 'address' => 'Via Santa Chiara 26, Ravello'],
            'فندق بيلموند كاروسو' => ['title' => 'Belmond Hotel Caruso', 'address' => 'Piazza San Giovanni del Toro 2, Ravello'],
            'قصر مارغريتا باسيليكاتا' => ['title' => 'Palazzo Margherita Basilicata', 'address' => 'Corso Umberto 64, Bernalda'],
            'فندق هاسلر روما' => ['title' => 'Hotel Hassler Roma', 'address' => 'Piazza Trinità dei Monti 6, Rome'],

            'فندق ريتز مدريد' => ['title' => 'Hotel Ritz Madrid', 'address' => 'Plaza de la Lealtad 5, Madrid'],
            'فندق فور سيزونز مدريد' => ['title' => 'Four Seasons Hotel Madrid', 'address' => 'Calle de Sevilla 3, Madrid'],
            'فندق آرتس برشلونة' => ['title' => 'Hotel Arts Barcelona', 'address' => 'Carrer de la Marina 19-21, Barcelona'],
            'فندق كاسا فوستر برشلونة' => ['title' => 'Hotel Casa Fuster Barcelona', 'address' => 'Passeig de Gràcia 132, Barcelona'],
            'فندق ألفونسو الثالث عشر إشبيلية' => ['title' => 'Hotel Alfonso XIII Seville', 'address' => 'Calle San Fernando 2, Seville'],
            'بارادور غرناطة' => ['title' => 'Parador de Granada', 'address' => 'Calle Real de la Alhambra, Granada'],
            'فندق فيلا ماغنا مدريد' => ['title' => 'Hotel Villa Magna Madrid', 'address' => 'Paseo de la Castellana 22, Madrid'],
            'فندق غران لا فلوريدا برشلونة' => ['title' => 'Gran Hotel La Florida Barcelona', 'address' => 'Carretera Vallvidrera al Tibidabo 83-93, Barcelona'],
            'فندق ماريا كريستينا سان سيباستيان' => ['title' => 'Hotel Maria Cristina San Sebastian', 'address' => 'Paseo República Argentina 4, San Sebastian'],
            'فندق هوسبيس قصر البايليو قرطبة' => ['title' => 'Hospes Palacio del Bailio Cordoba', 'address' => 'Calle Ramírez de las Casas Deza 10-12, Cordoba'],

            'فندق سافوي لندن' => ['title' => 'The Savoy London', 'address' => 'Strand, London WC2R 0EZ'],
            'فندق كلاريدجز لندن' => ['title' => 'Claridges London', 'address' => 'Brook Street, London W1K 4HR'],
            'فندق ريتز لندن' => ['title' => 'The Ritz London', 'address' => '150 Piccadilly, London W1J 9BR'],
            'فندق لانغهام لندن' => ['title' => 'The Langham London', 'address' => '1C Portland Place, London W1B 1JA'],
            'فندق شانغريلا في ذا شارد' => ['title' => 'Shangri-La Hotel at The Shard', 'address' => '31 St Thomas Street, London SE1 9QU'],
            'فندق كونوت لندن' => ['title' => 'The Connaught London', 'address' => 'Carlos Place, London W1K 2AL'],
            'فندق كورينثيا لندن' => ['title' => 'Corinthia Hotel London', 'address' => 'Whitehall Place, London SW1A 2BD'],
            'فندق دورتشستر لندن' => ['title' => 'The Dorchester London', 'address' => '53 Park Lane, London W1K 1QA'],
            'فندق روزوود لندن' => ['title' => 'Rosewood London', 'address' => '252 High Holborn, London WC1V 7EN'],
            'فندق ذا نيد لندن' => ['title' => 'The Ned London', 'address' => '27 Poultry, London EC2R 8AJ'],

            'فندق ريتز كارلتون طوكيو' => ['title' => 'The Ritz-Carlton Tokyo', 'address' => '9-7-1 Akasaka, Minato City, Tokyo'],
            'فندق أمان طوكيو' => ['title' => 'Aman Tokyo', 'address' => '1-5-6 Otemachi, Chiyoda City, Tokyo'],
            'فندق بارك حياة طوكيو' => ['title' => 'Park Hyatt Tokyo', 'address' => '3-7-1-2 Nishi Shinjuku, Shinjuku City, Tokyo'],
            'فندق فور سيزونز طوكيو في مارونوتشي' => ['title' => 'Four Seasons Hotel Tokyo at Marunouchi', 'address' => '1-11-1 Marunouchi, Chiyoda City, Tokyo'],
            'فندق بينينسولا طوكيو' => ['title' => 'The Peninsula Tokyo', 'address' => '1-8-1 Yurakucho, Chiyoda City, Tokyo'],
            'فندق هوشينويا طوكيو' => ['title' => 'Hoshinoya Tokyo', 'address' => '1-9-1 Otemachi, Chiyoda City, Tokyo'],
            'فندق إمبريال طوكيو' => ['title' => 'Imperial Hotel Tokyo', 'address' => '1-1-1 Uchisaiwaicho, Chiyoda City, Tokyo'],
            'فندق شانغريلا طوكيو' => ['title' => 'Shangri-La Hotel Tokyo', 'address' => '1-8-3 Marunouchi, Chiyoda City, Tokyo'],
            'فندق محطة طوكيو' => ['title' => 'The Tokyo Station Hotel', 'address' => '1-9-1 Marunouchi, Chiyoda City, Tokyo'],
            'فندق ماندارين أورينتال طوكيو' => ['title' => 'Mandarin Oriental Tokyo', 'address' => '2-1-1 Nihonbashi Muromachi, Chuo City, Tokyo'],

            'فندق بينينسولا بكين' => ['title' => 'The Peninsula Beijing', 'address' => '8 Goldfish Lane, Wangfujing, Beijing'],
            'فندق فور سيزونز بكين' => ['title' => 'Four Seasons Hotel Beijing', 'address' => '48 Liangmaqiao Road, Beijing'],
            'فندق ريتز كارلتون بكين' => ['title' => 'The Ritz-Carlton Beijing', 'address' => '83A Jianguo Road, Beijing'],
            'فندق بارك حياة بكين' => ['title' => 'Park Hyatt Beijing', 'address' => '2 Jianguomenwai Avenue, Beijing'],
            'فندق شانغريلا بكين' => ['title' => 'Shangri-La Hotel Beijing', 'address' => '29 Zizhuyuan Road, Beijing'],
            'فندق سانت ريجيس بكين' => ['title' => 'The St. Regis Beijing', 'address' => '21 Jianguomenwai Avenue, Beijing'],
            'فندق غراند حياة بكين' => ['title' => 'Grand Hyatt Beijing', 'address' => '1 East Chang An Avenue, Beijing'],
            'فندق روزوود بكين' => ['title' => 'Rosewood Beijing', 'address' => 'Jing Guang Centre, Hujialou, Beijing'],
            'فندق نو بكين' => ['title' => 'NUO Hotel Beijing', 'address' => '2A Jiangtai Road, Beijing'],
            'فندق أوبوزيت هاوس بكين' => ['title' => 'The Opposite House Beijing', 'address' => '11 Sanlitun Road, Beijing'],

            'فندق أوبيروي نيودلهي' => ['title' => 'The Oberoi New Delhi', 'address' => 'Dr. Zakir Hussain Marg, New Delhi'],
            'قصر ليلا نيودلهي' => ['title' => 'The Leela Palace New Delhi', 'address' => 'Diplomatic Enclave, New Delhi'],
            'قصر تاج محل مومباي' => ['title' => 'Taj Mahal Palace Mumbai', 'address' => 'Apollo Bunder, Mumbai'],
            'فندق أوبيروي مومباي' => ['title' => 'The Oberoi Mumbai', 'address' => 'Nariman Point, Mumbai'],
            'فندق فور سيزونز مومباي' => ['title' => 'Four Seasons Hotel Mumbai', 'address' => '114 Dr. E Moses Road, Mumbai'],
            'قصر ليلا أودايبور' => ['title' => 'The Leela Palace Udaipur', 'address' => 'Lake Pichola, Udaipur'],
            'قصر تاج البحيرة أودايبور' => ['title' => 'Taj Lake Palace Udaipur', 'address' => 'Pichola Lake, Udaipur'],
            'قصر رامباغ جايبور' => ['title' => 'Rambagh Palace Jaipur', 'address' => 'Bhawani Singh Road, Jaipur'],
            'فندق أوبيروي راجفيلاس جايبور' => ['title' => 'The Oberoi Rajvilas Jaipur', 'address' => 'Goner Road, Jaipur'],
            'فندق آي تي سي غراند تشولا تشيناي' => ['title' => 'ITC Grand Chola Chennai', 'address' => '63 Mount Road, Chennai'],

            'قصر كوباكابانا ريو دي جانيرو' => ['title' => 'Copacabana Palace Rio de Janeiro', 'address' => 'Avenida Atlântica 1702, Rio de Janeiro'],
            'فندق فاسانو ريو دي جانيرو' => ['title' => 'Fasano Hotel Rio de Janeiro', 'address' => 'Avenida Vieira Souto 80, Rio de Janeiro'],
            'فندق يونيك ساو باولو' => ['title' => 'Hotel Unique São Paulo', 'address' => 'Avenida Brigadeiro Luís Antônio 4700, São Paulo'],
            'فندق فاسانو ساو باولو' => ['title' => 'Fasano São Paulo', 'address' => 'Rua Vittorio Fasano 88, São Paulo'],
            'فندق غراند حياة ساو باولو' => ['title' => 'Grand Hyatt São Paulo', 'address' => 'Avenida das Nações Unidas 13301, São Paulo'],
            'فندق إيميليانو ساو باولو' => ['title' => 'Hotel Emiliano São Paulo', 'address' => 'Rua Oscar Freire 384, São Paulo'],
            'فندق روزوود ساو باولو' => ['title' => 'Rosewood São Paulo', 'address' => 'Alameda Santos 2200, São Paulo'],
            'فندق جي دبليو ماريوت ريو دي جانيرو' => ['title' => 'JW Marriott Hotel Rio de Janeiro', 'address' => 'Avenida Atlântica 2600, Rio de Janeiro'],
            'فندق فيرمونت ريو دي جانيرو كوباكابانا' => ['title' => 'Fairmont Rio de Janeiro Copacabana', 'address' => 'Avenida Atlântica 4240, Rio de Janeiro'],
            'فندق فاسانو بوا فيستا' => ['title' => 'Hotel Fasano Boa Vista', 'address' => 'Fazenda Boa Vista, Porto Feliz'],

            'فندق فيرمونت شاتو بحيرة لويز' => ['title' => 'Fairmont Chateau Lake Louise', 'address' => '111 Lake Louise Drive, Lake Louise, AB'],
            'فندق فور سيزونز تورونتو' => ['title' => 'Four Seasons Hotel Toronto', 'address' => '60 Yorkville Avenue, Toronto, ON'],
            'فندق ريتز كارلتون تورونتو' => ['title' => 'The Ritz-Carlton Toronto', 'address' => '181 Wellington Street West, Toronto, ON'],
            'فندق فيرمونت رويال يورك تورونتو' => ['title' => 'Fairmont Royal York Toronto', 'address' => '100 Front Street West, Toronto, ON'],
            'فندق روزوود جورجيا فانكوفر' => ['title' => 'Rosewood Hotel Georgia Vancouver', 'address' => '801 West Georgia Street, Vancouver, BC'],
            'فندق فور سيزونز فانكوفر' => ['title' => 'Four Seasons Hotel Vancouver', 'address' => '791 West Georgia Street, Vancouver, BC'],
            'فندق فيرمونت فانكوفر' => ['title' => 'Fairmont Hotel Vancouver', 'address' => '900 West Georgia Street, Vancouver, BC'],
            'شاتو فرونتيناك مدينة كيبيك' => ['title' => 'Château Frontenac Quebec City', 'address' => '1 Rue des Carrières, Quebec City, QC'],
            'فندق فور سيزونز مونتريال' => ['title' => 'Four Seasons Hotel Montreal', 'address' => '1440 Rue de la Montagne, Montreal, QC'],
            'فندق ريتز كارلتون مونتريال' => ['title' => 'The Ritz-Carlton Montreal', 'address' => '1228 Sherbrooke Street West, Montreal, QC'],

            'فندق بارك حياة سيدني' => ['title' => 'Park Hyatt Sydney', 'address' => '7 Hickson Road, Sydney, NSW'],
            'فندق فور سيزونز سيدني' => ['title' => 'Four Seasons Hotel Sydney', 'address' => '199 George Street, Sydney, NSW'],
            'فندق لانغهام سيدني' => ['title' => 'The Langham Sydney', 'address' => '89-113 Kent Street, Sydney, NSW'],
            'فندق شانغريلا سيدني' => ['title' => 'Shangri-La Hotel Sydney', 'address' => '176 Cumberland Street, Sydney, NSW'],
            'أبراج كراون ملبورن' => ['title' => 'Crown Towers Melbourne', 'address' => '8 Whiteman Street, Melbourne, VIC'],
            'فندق بارك حياة ملبورن' => ['title' => 'Park Hyatt Melbourne', 'address' => '1 Parliament Square, Melbourne, VIC'],
            'فندق لانغهام ملبورن' => ['title' => 'The Langham Melbourne', 'address' => '1 Southgate Avenue, Melbourne, VIC'],
            'فندق كومو الخزانة بيرث' => ['title' => 'COMO The Treasury Perth', 'address' => '1 Cathedral Avenue, Perth, WA'],
            'فندق إمبوريوم ساوث بانك بريسبان' => ['title' => 'Emporium Hotel South Bank Brisbane', 'address' => '267 Grey Street, Brisbane, QLD'],
            'فندق كاليل بريسبان' => ['title' => 'The Calile Hotel Brisbane', 'address' => '39 James Street, Brisbane, QLD'],

            'فندق فور سيزونز مكسيكو سيتي' => ['title' => 'Four Seasons Hotel Mexico City', 'address' => 'Paseo de la Reforma 500, Mexico City'],
            'فندق سانت ريجيس مكسيكو سيتي' => ['title' => 'The St. Regis Mexico City', 'address' => 'Paseo de la Reforma 439, Mexico City'],
            'فندق جي دبليو ماريوت مكسيكو سيتي' => ['title' => 'JW Marriott Hotel Mexico City', 'address' => 'Andrés Bello 29, Mexico City'],
            'فندق غراند فييستا أمريكانا تشابولتيبيك' => ['title' => 'Grand Fiesta Americana Chapultepec', 'address' => 'Mariano Escobedo 756, Mexico City'],
            'فندق بريزيدنتي إنتركونتيننتال' => ['title' => 'Hotel Presidente InterContinental', 'address' => 'Campos Elíseos 218, Mexico City'],
            'فندق روزوود سان ميغيل دي أليندي' => ['title' => 'Rosewood San Miguel de Allende', 'address' => 'Nemesio Diez 11, San Miguel de Allende'],
            'فندق بيلموند كاسا دي سييرا نيفادا' => ['title' => 'Belmond Casa de Sierra Nevada', 'address' => 'Hospicio 35, San Miguel de Allende'],
            'فندق غراند فيلاس ريفييرا مايا' => ['title' => 'Grand Velas Riviera Maya', 'address' => 'Carretera Cancún-Tulum Km 62, Playa del Carmen'],
            'فندق روزوود مايكوبا' => ['title' => 'Rosewood Mayakoba', 'address' => 'Carretera Federal Cancun-Playa del Carmen Km 298'],
            'فندق بانيان تري مايكوبا' => ['title' => 'Banyan Tree Mayakoba', 'address' => 'Carretera Federal Cancun-Playa del Carmen Km 298'],

            'فندق فور سيزونز إسطنبول في السلطان أحمد' => ['title' => 'Four Seasons Hotel Istanbul at Sultanahmet', 'address' => 'Tevkifhane Sokak No 1, Istanbul'],
            'قصر تشيراغان كيمبينسكي إسطنبول' => ['title' => 'Çırağan Palace Kempinski Istanbul', 'address' => 'Çırağan Caddesi 32, Istanbul'],
            'فندق ريتز كارلتون إسطنبول' => ['title' => 'The Ritz-Carlton Istanbul', 'address' => 'Suzer Plaza, Askerocagi Caddesi No 6, Istanbul'],
            'فندق شانغريلا البوسفور إسطنبول' => ['title' => 'Shangri-La Bosphorus Istanbul', 'address' => 'Sinanpaşa Mahallesi, Hayrettin İskelesi Sokak 1, Istanbul'],
            'فندق بارك حياة إسطنبول ماتشكا بالاس' => ['title' => 'Park Hyatt Istanbul Macka Palas', 'address' => 'Bronz Sokak No 4, Istanbul'],
            'فندق سيكس سينسز كابلانكايا' => ['title' => 'Six Senses Kaplankaya', 'address' => 'Kaplankaya, Bodrum'],
            'فندق ماندارين أورينتال بودروم' => ['title' => 'Mandarin Oriental Bodrum', 'address' => 'Cennet Koyu, Bodrum'],
            'فندق إديشن بودروم' => ['title' => 'The Edition Bodrum', 'address' => 'Yalikavak Marina, Bodrum'],
            'فندق سويس أوتيل البوسفور إسطنبول' => ['title' => 'Swissotel The Bosphorus Istanbul', 'address' => 'Visnezade Mahallesi, Acisu Sokak No 19, Istanbul'],
            'فندق كونراد إسطنبول البوسفور' => ['title' => 'Conrad Istanbul Bosphorus', 'address' => 'Cihannüma Mahallesi, Saray Caddesi No 5, Istanbul'],

            'فندق أورينتال بانكوك' => ['title' => 'The Oriental Bangkok', 'address' => '48 Oriental Avenue, Bangkok'],
            'فندق فور سيزونز بانكوك' => ['title' => 'Four Seasons Hotel Bangkok', 'address' => '155 Rajadamri Road, Bangkok'],
            'فندق سانت ريجيس بانكوك' => ['title' => 'The St. Regis Bangkok', 'address' => '159 Rajadamri Road, Bangkok'],
            'فندق بارك حياة بانكوك' => ['title' => 'Park Hyatt Bangkok', 'address' => '88 Wireless Road, Bangkok'],
            'فندق شانغريلا بانكوك' => ['title' => 'Shangri-La Hotel Bangkok', 'address' => '89 Soi Wat Suan Plu, Bangkok'],
            'فندق روزوود بانكوك' => ['title' => 'Rosewood Bangkok', 'address' => '1041/38 Ploenchit Road, Bangkok'],
            'منتجع فور سيزونز تشيانغ ماي' => ['title' => 'Four Seasons Resort Chiang Mai', 'address' => '502 Moo 1, Mae Rim-Samoeng Old Road, Chiang Mai'],
            'فندق أنانتارا المثلث الذهبي' => ['title' => 'Anantara Golden Triangle', 'address' => '229 Moo 1, Chiang Saen, Chiang Rai'],
            'فندق سيكس سينسز ياو نوي' => ['title' => 'Six Senses Yao Noi', 'address' => '56 Moo 5, Koh Yao Noi, Phang Nga'],
            'فندق أمانبوري فوكيت' => ['title' => 'Amanpuri Phuket', 'address' => 'Pansea Beach, Phuket'],

            'فندق بارك حياة سيول' => ['title' => 'Park Hyatt Seoul', 'address' => '606 Teheran-ro, Gangnam-gu, Seoul'],
            'فندق فور سيزونز سيول' => ['title' => 'Four Seasons Hotel Seoul', 'address' => '97 Saemunan-ro, Jongno-gu, Seoul'],
            'فندق شيلا سيول' => ['title' => 'The Shilla Seoul', 'address' => '249 Dongho-ro, Jung-gu, Seoul'],
            'فندق غراند حياة سيول' => ['title' => 'Grand Hyatt Seoul', 'address' => '322 Sowol-ro, Yongsan-gu, Seoul'],
            'فندق جي دبليو ماريوت سيول' => ['title' => 'JW Marriott Hotel Seoul', 'address' => '176 Sinbanpo-ro, Seocho-gu, Seoul'],
            'فندق لوته سيول' => ['title' => 'Lotte Hotel Seoul', 'address' => '30 Eulji-ro, Jung-gu, Seoul'],
            'فندق كونراد سيول' => ['title' => 'Conrad Seoul', 'address' => '10 Gukjegeumyung-ro, Yeongdeungpo-gu, Seoul'],
            'فندق بانيان تري كلوب وسبا سيول' => ['title' => 'Banyan Tree Club & Spa Seoul', 'address' => '60 Jangchungdan-ro, Jung-gu, Seoul'],
            'فندق سيغنيل سيول' => ['title' => 'Signiel Seoul', 'address' => '300 Olympic-ro, Songpa-gu, Seoul'],
            'فندق ويستن تشوسون سيول' => ['title' => 'The Westin Chosun Seoul', 'address' => '106 Sogong-ro, Jung-gu, Seoul'],

            'برج العرب جميرا' => ['title' => 'Burj Al Arab Jumeirah', 'address' => 'Jumeirah Beach Road, Dubai'],
            'منتجع فور سيزونز دبي في شاطئ جميرا' => ['title' => 'Four Seasons Resort Dubai at Jumeirah Beach', 'address' => 'Jumeirah Beach Road, Dubai'],
            'فندق ريتز كارلتون دبي' => ['title' => 'The Ritz-Carlton Dubai', 'address' => 'Dubai International Financial Centre, Dubai'],
            'فندق بارك حياة دبي' => ['title' => 'Park Hyatt Dubai', 'address' => 'Dubai Creek Golf & Yacht Club, Dubai'],
            'أتلانتس النخلة' => ['title' => 'Atlantis The Palm', 'address' => 'Crescent Road, The Palm Jumeirah, Dubai'],
            'قصر الإمارات أبوظبي' => ['title' => 'Emirates Palace Abu Dhabi', 'address' => 'West Corniche Road, Abu Dhabi'],
            'فندق سانت ريجيس أبوظبي' => ['title' => 'The St. Regis Abu Dhabi', 'address' => 'Nation Towers, Corniche, Abu Dhabi'],
            'فندق فور سيزونز أبوظبي' => ['title' => 'Four Seasons Hotel Abu Dhabi', 'address' => 'Al Maryah Island, Abu Dhabi'],
            'فندق روزوود أبوظبي' => ['title' => 'Rosewood Abu Dhabi', 'address' => 'Al Maryah Island, Abu Dhabi'],
            'فندق شانغريلا قرية البري' => ['title' => 'Shangri-La Hotel Qaryat Al Beri', 'address' => 'Qaryat Al Beri, Abu Dhabi'],

            'مارينا باي ساندز' => ['title' => 'Marina Bay Sands', 'address' => '10 Bayfront Avenue, Singapore'],
            'فندق ريتز كارلتون ميلينيا سنغافورة' => ['title' => 'The Ritz-Carlton Millenia Singapore', 'address' => '7 Raffles Avenue, Singapore'],
            'فندق فور سيزونز سنغافورة' => ['title' => 'Four Seasons Hotel Singapore', 'address' => '190 Orchard Boulevard, Singapore'],
            'فندق شانغريلا سنغافورة' => ['title' => 'Shangri-La Hotel Singapore', 'address' => '22 Orange Grove Road, Singapore'],
            'فندق سانت ريجيس سنغافورة' => ['title' => 'The St. Regis Singapore', 'address' => '29 Tanglin Road, Singapore'],
            'فندق كابيلا سنغافورة' => ['title' => 'Capella Singapore', 'address' => '1 The Knolls, Sentosa Island, Singapore'],
            'فندق رافلز سنغافورة' => ['title' => 'Raffles Hotel Singapore', 'address' => '1 Beach Road, Singapore'],
            'فندق بارك حياة سنغافورة' => ['title' => 'Park Hyatt Singapore', 'address' => '10 Scotts Road, Singapore'],
            'فندق كونراد سنتينيال سنغافورة' => ['title' => 'Conrad Centennial Singapore', 'address' => '2 Temasek Boulevard, Singapore'],
            'فندق ماندارين أورينتال سنغافورة' => ['title' => 'Mandarin Oriental Singapore', 'address' => '5 Raffles Avenue, Singapore']
        ];

        foreach ($originalHotels as $arabicTitle => $originalData) {
            Hotel::where('title', $arabicTitle)->update([
                'title' => $originalData['title'],
                'address' => $originalData['address']
            ]);
        }
    }
}