<?php

return [
    'use_external' => env('USE_EXTERNAL_IMAGES', true),

    'google_drive' => [
        'base_url' => env('GOOGLE_DRIVE_BASE_URL', 'https://lh3.googleusercontent.com/d/'),
    ],
    'hotels' => [
        'australia' => [
            'como_the_treasury_perth' => '1UKWmBzUBfTnubk2uobVYoI5WvEGF5SoD',
            'crown_towers_melbourne' => '1M_aE5q22AaG_lP8ezK6DfGC6LgkG7ZaK',
            'emporium_hotel_south_bank_brisbane' => '1h3e0lcfSVFF0dkpRUalnQxqjzoSVOu1z',
            'four_seasons_hotel_sydney' => '1qYtOCtEKfHoX4_X48ytFdeBnDMFv6MBi',
            'park_hyatt_melbourne' => '1xCXTtgyOLvQ-XKy7EDELP9f0dgiva4G1',
            'park_hyatt_sydney' => '1wIPhWTKGPRSu5Pf_CEDXp1zZ6bjfToIt',
            'shangri_la_hotel_sydney' => '1v5E3cceVkiAm0De-UvCOs8OSFp4Rn8sJ',
            'the_calile_hotel_brisbane' => '1MnwiaE7zU1vMRQT8Jdciuv5HVGEcMxpg',
            'the_langham_melbourne' => '1rPqBZJL1ADIxmcO2pe2yCXjrdQlT0BlF',
            'the_langham_sydney' => '1OHxP5w0NuF2OyR9ybYl1ovrz3i5EexH2',
        ],
        'brazil' => [
            'copacabana_palace_rio_de_janeiro' => '1NzJJTw0zJ0lbqlIUWvCvjjF_qHAHrrzr',
            'fairmont_rio_de_janeiro_copacabana' => '1EfIZVqqAK3kbGzVs7x6qVMeeTGARCX6z',
            'fasano_hotel_rio_de_janeiro' => '1jj5rnlkEywfmZVZllddpEjc3Yu7lA7dm',
            'fasano_são_paulo' => '1pXBuZFkI6TFp8TOKgMLx7nuWdRPlIYfR',
            'grand_hyatt_são_paulo' => '1ag1_nc4yA5srqdholoDvsi-mi41AnBOR',
            'hotel_emiliano_são_paulo' => '1oYDiD_SByqnOL9rnpAgCBIwc0084_t97',
            'hotel_fasano_boa_vista' => '1OOSEdF7mwVxZkwc_MuQ_fds8B42qk0SK',
            'hotel_unique_são_paulo' => '1Ci3i0kdwj9inoJn0kn2zsow14_bnbOah',
            'jw_marriott_hotel_rio_de_janeiro' => '152xpoWF2Ul0H_C_Laiuy6PdSUiZ2mYCu',
            'rosewood_são_paulo' => '1R232APaA8v1feV6aWQocFtQjErkw5IYA',
        ],
        'canada' => [
            'château_frontenac_quebec_city' => '1voEs4_nMsPtnjby-1GrSnbT-By8soZDV',
            'fairmont_chateau_lake_louise' => '1tdEDk-pz_vs_KHwtpwBWeSp-6KFzYtf3',
            'fairmont_hotel_vancouver' => '1_ICF0t1bEnGGXTR-tvqfWEcvUvuHh4kZ',
            'fairmont_royal_york_toronto' => '1YlWxmPHgr4JUCEulTdEVcex-I7bmj2JS',
            'four_seasons_hotel_montreal' => '1-MzBI2JkM4Fa1v7OI2tOORwjElNyu1AI',
            'four_seasons_hotel_toronto' => '1rS33nYyMLR0olzb_YN3jTx2t1fqO3iEv',
            'four_seasons_hotel_vancouver' => '1COXRQiQPvVZqj7gVX5y8WNgTl4P9ED3E',
            'rosewood_hotel_georgia_vancouver' => '17vIpUh3b_ho42ICOvdOh9p0H3CzaS-FI',
            'the_ritz_carlton_montreal' => '1iewBpKF3qpZGm02PfQiVW6CtG-eoGxsx',
            'the_ritz_carlton_toronto' => '1ozTfMXDn0m8j_Ygd5OcgZkqmK5xAI4ZM',
        ],
        'china' => [
            'four_seasons_hotel_beijing' => '1oCYfmVjZ4bC489oNSA54scpKsbb9u0Iv',
            'grand_hyatt_beijing' => '1EFpD6AdcTmjLEg0rMqSmoK7jATaVRmAK',
            'nuo_hotel_beijing' => '13RB-YJ-Jnaaq8Kuwwid1I5c_tAabG7zf',
            'park_hyatt_beijing' => '11DeRzaY6LGRvvwf2RwvVXnLZpFAelHQ1',
            'rosewood_beijing' => '1ivLLJtzUYTUZcVgu-xD22nw_ixd9bTsN',
            'shangri_la_hotel_beijing' => '1iAI5heXziBBwotvO21P_kEyz8V4xSSI7',
            'the_opposite_house_beijing' => '1-dD-mQwAtv22_U3fP0kbWENU5IXaqbbq',
            'the_peninsula_beijing' => '1BGG5B5KZgLU4P1ItzghxPCaohiQ_gCqA',
            'the_ritz_carlton_beijing' => '1GMWpKHQESXIXPGlldt8rHZ3cEPlJoKNt',
            'the_st_regis_beijing' => '1NoIYcQQ5b12zOKtelCsvGt0iHKCYoR9u',
        ],
        'france' => [
            'four_seasons_hotel_george_v' => '1LSxFThDgBgFLhEjNIL9MxfYpXHq_uBbd',
            'hotel_de_crillon' => '14oM45a42bBMkQHfiXZ20vhsQ2cvVfLgv',
            'hotel_lutetia' => '1ekE73Whtf1ZCXJlWbDIhyZ5Mq3wB8vwY',
            'hotel_plaza_athénée' => '1ueiffAnjxYzVNH-crKY6f3Ogut2nA6K-',
            'la_réserve_paris' => '13DmBJcbP4hRTBGgqGDKJWXlV6eVg9Vtz',
            'le_bristol_paris' => '1ywThlmnDgP7vGw61u2Fs_qhi00S-OTls',
            'le_meurice' => '1rqShN9FJsgFedvmirJRIva4t--WA54f1',
            'park_hyatt_paris_vendôme' => '1PWOzmSPIu3rrjnJlog1FxmCiD6kML2Zi',
            'shangri_la_hotel_paris' => '1BOVLCiBIpdPBHF41uRjHWofT6a3Kmqdh',
            'the_ritz_paris' => '14GsJDW3FPfcbvoLVS8pu17nEjs825d_9',
        ],
        'germany' => [
            'das_stue_berlin' => '1uhiGMWI93_jf3MzSoHQFcaZXfiSb-TZZ',
            'grand_hyatt_berlin' => '1Ac4b_GGstb68fGrFb9S33r18CjxSWlSa',
            'hotel_adlon_kempinski_berlin' => '1hoQxIFsFp9Ck9PdGofvnzbA_mjFJE5ja',
            'hotel_brandenburger_hof' => '13-5d6qI9KRc2pxJS-SDEw8ps91pZX0Oy',
            'hotel_de_rome_berlin' => '1Xyday3SDAbPMS15gqcLd-8-N-r_Fzh30',
            'orania_berlin' => '1Pz2NhnkKBMWb9F9J2S_8M_hV_1vZ5FLi',
            'regent_berlin' => '10hNlZulcwiqKFbuv_CdtrxDNiY8nWC-F',
            'soho_house_berlin' => '1RHskGgDy8mj1mpdO3qqM669GTOHoUmuV',
            'the_ritz_carlton_berlin' => '1zMseYFURxoQVtYZcr6x3u6FEdVdOgg4p',
            'titanic_gendarmenmarkt_berlin' => '17AHvqi7f85cUbQSa9DLjNeCxNQnzID-2',
        ],
        'india' => [
            'four_seasons_hotel_mumbai' => '1MdVthy7wJK4O-6ix46wl6N-AHi-1mP1O',
            'itc_grand_chola_chennai' => '12c64x-dD1wZ39FtQB24bEO_CnpJFhoq6',
            'rambagh_palace_jaipur' => '1t1tPZ_NFSWJQI38ByhjM2hLS0MevsDDB',
            'taj_lake_palace_udaipur' => '1Ez4AUboDThcHY4d-LBIzRBT5fO0PmFQb',
            'taj_mahal_palace_mumbai' => '1OerReKRmOVE2Iu4ph8YH-wJcZ4lS0_6D',
            'the_leela_palace_new_delhi' => '1xOfg4HhiR3_vJbmdsUZpTCqN6AflEcNX',
            'the_leela_palace_udaipur' => '1WWwxx1nxWWqOdbZa52F974HyERopyOcv',
            'the_oberoi_mumbai' => '1RNGdDs_ZWb0SjGTT7OYASr7Qx5n6PR5P',
            'the_oberoi_new_delhi' => '1HoIhyKH1VIxwpll3vg9BEfGdrlpwifP0',
            'the_oberoi_rajvilas_jaipur' => '1J_SFJdNjVG9uUFOt5oUwXVnPEXVoSb6B',
        ],
        'italy' => [
            'belmond_hotel_caruso' => '1qzgnPQInd2Z2tsxHzfVWi1LZG6mENwsl',
            'four_seasons_hotel_milano' => '1A7qvi33nW0Q_Q6bxdEsDqYAumetWzpda',
            'gritti_palace_venice' => '1MQJXLIzy0L0l9H9-mga_Ev8q6UD8_t5r',
            'hotel_de_russie_rome' => '1Uuvq5PXpbuKWbAZ4QFJ-01GsLi8UOBPf',
            'hotel_hassler_roma' => '1fHf6Mk0jxWvMMUhcaDk7LuzVo1ZawTtK',
            'hotel_splendido_portofino' => '11GHXG4RtkYImaHpVzypejE0MkpSzdZN_',
            'hotel_villa_cimbrone_ravello' => '1nVCgyI6eh3f1L2_QhtpchorDpeHs-OxA',
            'palazzo_margherita_basilicata' => '1tVAXIBMtcj9XT0-kOdj51LJHEudTm6oA',
            'the_st_regis_rome' => '1Ujv2F5qfYQRULKroUpjvszrcIYNZbWmx',
            'villa_san_martino_martina_franca' => '1-oYBpv_WZQUqNplMQp1vvlRWv-Vrpp1-',
        ],
        'japan' => [
            'aman_tokyo' => '1_HMjBgiLdVvyZ8aFPZ3_R9eBzbDqwO-d',
            'four_seasons_hotel_tokyo_at_marunouchi' => '1Eq0ckXvjpnO8iPqXJD_QSRxJuVXVdM7r',
            'hoshinoya_tokyo' => '1FXT5jkvZZJ14RPQwFXnF8cjSC_fuIgq8',
            'imperial_hotel_tokyo' => '1EhKcuo4j0tSXNRU2a14URUSTq35IfmgM',
            'mandarin_oriental_tokyo' => '1lloltcoD26AbK9ZsErYPJHAlIg2lK-QC',
            'park_hyatt_tokyo' => '1crm7xpjEOhJQbfzWl6cGb_PANkGeRE5T',
            'shangri_la_hotel_tokyo' => '1j7YXZuRA__rJ0v5OUBCbbN7oSuQ05U0V',
            'the_peninsula_tokyo' => '1UZk_WO6Q9kZg38Kjby3RGJB8OfoG4LOA',
            'the_ritz_carlton_tokyo' => '1i_R3-ivahHSY2s0xuP1BuE0cDiYodiDz',
            'the_tokyo_station_hotel' => '1KtuHTgF1xqZ8Sux_AKurjRhysjjG6Gf4',
        ],
        'mexico' => [
            'banyan_tree_mayakoba' => '1NYoVnlvvwVRKnirvMyeEMMZIZq1T-1gT',
            'belmond_casa_de_sierra_nevada' => '154t2d4rVr_t80Wzrmw-q7k4z0XV1rpeO',
            'four_seasons_hotel_mexico_city' => '1i7J2sXwBNQ39YNXzQesPxM4yV2HQoeUa',
            'grand_fiesta_americana_chapultepec' => '1rK2oaogLjFS0o5k26XDwToXnMhvB5Tkz',
            'grand_velas_riviera_maya' => '1UdrFiC2dhFJ1Ss1HAohx9pxPgXG5Quou',
            'hotel_presidente_intercontinental' => '1BqfDbMY2lRRQVw-3rVdpTKfBY9WW73e_',
            'jw_marriott_hotel_mexico_city' => '1MVETVag0fQZ1OBbHqEBoaY2fnR_L2JEu',
            'rosewood_mayakoba' => '1NU9hlyzh-KGEzQnPv_eoUEYLV-RKW7XR',
            'rosewood_san_miguel_de_allende' => '1K1bBR22GC_KLsl6rX-zQ_HJsny46wR1v',
            'the_st_regis_mexico_city' => '12UuExgeTuU1SP3Y-5T7E21OiCyLD4ac4',
        ],
        'norway' => [
            'amerikalinjen_oslo' => '1wcRveOrJyx_h3ObHKfNgb-bhx9cVYtTS',
            'clarion_hotel_the_hub' => '1negncXk5fBaKMHUIzggEDgO6FreD6qD0',
            'grand_hotel_oslo' => '1MHSV_9z-MVy3hV6dSGxB7XyEka738FGn',
            'hotel_bristol_oslo' => '1F0s0VSFNRQU6zxJtTtmJpccUggHnZ9ND',
            'hotel_continental_oslo' => '1Hqcxl9-CoFdiMkdSfEOQ1-SumzMmaU_3',
            'radisson_blu_plaza_hotel_oslo' => '1XXPpAyuHdiiGAGb7RX3fDaNUr8dtOxIR',
            'scandic_holmenkollen_park' => '1OXI9tOpK8OiulMNIV2run3w7nRlwFthf',
            'scandic_vulkan' => '1LnZScMHF-ATOU1ZUrg2ghg6N_zRJIL31',
            'the_thief_oslo' => '1vmJK8KfBVEriNA0HkP1GkQPPlNB_qb0Z',
            'villa_frogner' => '12zBFhkKTcT7m0OdTtB38AxKQdxCcOf1J',
        ],
        'russia' => [
            'ararat_park_hyatt_moscow' => '1SOEfNNHMFa_z29NWFzdu0-tNjirM3wEt',
            'baltschug_kempinski_moscow' => '1yI8GH9q0MbWq477Do4G9X4jY4r0E60IL',
            'four_seasons_hotel_moscow' => '1f62-ehRcRgashLjRcCuGa_aYgOgR9N66',
            'hotel_metropol_moscow' => '1DG4lsKQyh92J5_xnepYBaEQsXXZbksWx',
            'hotel_national_moscow' => '11RYLq6hwflc4YkCPvQ5fRj-BjV4POiJX',
            'lotte_hotel_moscow' => '1EkQ4yF2_bfzf7OCzK-oQ4eUsBrDWUXV3',
            'radisson_collection_hotel_moscow' => '1mJ896WqdG8U1lH0kqkUSeB3u7tue20L0',
            'swissotel_krasnye_holmy_moscow' => '1OJJZlKJg16XmU5MdXW74fKTMOZ_bmof4',
            'the_ritz_carlton_moscow' => '1jK0_p8wVwXhkbFL2ZO6JBfrRKY_wCKKv',
            'the_st_regis_moscow' => '1IKrKOR30OMrJgcY0NoE3nbI_5jThp_Im',
        ],
        'singapore' => [
            'capella_singapore' => '16KJlPfISM64jllt_iYp6JsKuCfMIRnbi',
            'conrad_centennial_singapore' => '1L-GkMmv2qQZPbg9y5qkg6dS1ddEP76X4',
            'four_seasons_hotel_singapore' => '1v6Vc03vP8v1r7qyUCB9KIpILui-41zFv',
            'mandarin_oriental_singapore' => '14nXUn06a7fqvvC3oR5UIVa7BcfEcHyJR',
            'marina_bay_sands' => '1YIioQil7gNKTMKaTmuds6fLE-IAv1JSR',
            'park_hyatt_singapore' => '1KqdjIM3LZ9DTQVXm2dhzZ8RUlEgXloZC',
            'raffles_hotel_singapore' => '1nZDs6S5SRYLYw_j7LiwcjukOthRgCKsp',
            'shangri_la_hotel_singapore' => '1Qffme2gIhVUuSXnWDaXrWH9HNooyLKmm',
            'the_ritz_carlton_millenia_singapore' => '1-LKeVjF5J6XVz6QaQ03PgAD7NFdUGnWe',
            'the_st_regis_singapore' => '1PJPOPpZorxuqh9Y-smOeecnGMkGEuNHl',
        ],
        'south_korea' => [
            'banyan_tree_club_and_spa_seoul' => '1UY4BuIcSV9wVaXix5Ljnd3Xq2RzYfavD',
            'conrad_seoul' => '1C8jCuZnQTF0u-11OWfTOvrHKTgAgu8cK',
            'four_seasons_hotel_seoul' => '1IrZtR_8xM1I_ZW7dnae7NYDgZqJ7SCRA',
            'grand_hyatt_seoul' => '1mF5xSFv4NAS_W12SqIS4RcvasdDwU0uB',
            'jw_marriott_hotel_seoul' => '1TXZsicKMXPKVxyoeDaxWy8vu40Fqcqks',
            'lotte_hotel_seoul' => '1RKH_lvp-zILHbG4lrJyBsVJrS598RG1w',
            'park_hyatt_seoul' => '1bVOmbxfo7F9ASCrGcM7tYLF-Lk3fF0ij',
            'signiel_seoul' => '1vARCdfn-_UvCPEDgkTKT1jsm2GWeXQ7V',
            'the_shilla_seoul' => '1G7vhSlrzr494QiSIkNi7nBOvxRDNgcZ2',
            'the_westin_chosun_seoul' => '1845lc0cl1lS4u7-Km92hzGFqZYU5elUL',
        ],
        'spain' => [
            'four_seasons_hotel_madrid' => '1RPVMJ5b-xyNJF7BWUGUI_DhlmQ48VQyt',
            'gran_hotel_la_florida_barcelona' => '1YNi9nQ6xwJAaTbQrsWMrUsqDo5x-qQ0L',
            'hospes_palacio_del_bailio_cordoba' => '11lDHUvNNxiSeECRc-o7ir2BycAqFnPmV',
            'hotel_alfonso_xiii_seville' => '1J0fMcc7dNj9O_v8t8jrd1ThFakvTkfdR',
            'hotel_arts_barcelona' => '1Dg2XOlFRXsftz6gxdkDMgsv-FUlnJFu6',
            'hotel_casa_fuster_barcelona' => '1yAuRY7iZXg4uD_-c5LOZkjJrDmci9t4b',
            'hotel_maria_cristina_san_sebastian' => '13C3lN9eafoXApwFbU-qBgNotYSi409bD',
            'hotel_ritz_madrid' => '1m_kis4kyxgEYWxrO6Ym1-PcB_nXvj0WU',
            'hotel_villa_magna_madrid' => '1GCT1tmfjBSui5383TOb-0sCZ1WoawIOD',
            'parador_de_granada' => '1TLv06I4BLFI2UGGPxQCiekT5N0-x2EtM',
        ],
        'thailand' => [
            'amanpuri_phuket' => '1Mj58tG51v0LNTNcYHHFY8EsiPRGJ23zK',
            'anantara_golden_triangle' => '1PfQ8Nt61O1jalFakNvWmAEKwYQiY2piH',
            'four_seasons_hotel_bangkok' => '1B38mXm6eSFKUco6CXgYGhQL9CxQ1WHAt',
            'four_seasons_resort_chiang_mai' => '13KZjZqXnH3hBpsqHwTc82EJVkUAsIgz7',
            'park_hyatt_bangkok' => '1zf9Ix9-PEupyY0radN0OtbLBKYZe3k5D',
            'rosewood_bangkok' => '1PigyzLw6kla6ul1TSGwRFa5c242Uw_up',
            'shangri_la_hotel_bangkok' => '1JiBl-O8q5NCJk8Z6vnw-Rmweu09bgit_',
            'six_senses_yao_noi' => '1bE0iypEEDgu5si_e2Hq6XvzXfYVTxXYL',
            'the_oriental_bangkok' => '1g_LDTIAUvZTn107Z2i1KMM-wezYJsVNv',
            'the_st_regis_bangkok' => '1n-vUOSVwkab0kqIUyHpG6HQALUgDtXY-',
        ],
        'turkey' => [
            'conrad_istanbul_bosphorus' => '1uL288OUOz4zNFvxmouxRo_JXXQSJWBEc',
            'four_seasons_hotel_istanbul_at_sultanahmet' => '1f_5JnqrUnb8qCEOs1swzqFxdI854jPOB',
            'mandarin_oriental_bodrum' => '1O7muO5KzAKhbl9mtWdlNC8KQYGg62db3',
            'park_hyatt_istanbul_macka_palas' => '1bkiN7AQ2Gz3V1ypnqdC-GOkHcPa5qnA3',
            'shangri_la_bosphorus_istanbul' => '1rKUB_q7QC2-kjn00emXyhazi06OscpN7',
            'six_senses_kaplankaya' => '16-vgpl99t0uZb3pDNi-Wp39BWrGnMoAE',
            'swissotel_the_bosphorus_istanbul' => '10bE9O490sAgPo3groSDRIE35cK9zWj-x',
            'the_edition_bodrum' => '1jA1L2a9FuTWrs6UI5loSsCUYM2cCR9oP',
            'the_ritz_carlton_istanbul' => '1zii0yAevqvpFkqY4ux6ZwZ2P5DDrsRdz',
            'Çırağan_palace_kempinski_istanbul' => '1tfe5hnB3It3cUyedwHvj3fw-rfs_D1kF',
        ],
        'uae' => [
            'atlantis_the_palm' => '1D_Lk2rLXe4d2DmXMwufvgbRhd1qQGtWx',
            'burj_al_arab_jumeirah' => '1pxaTFZkDiKtbbi8Ul8paDnd0UMZ7lJ4w',
            'emirates_palace_abu_dhabi' => '1mUjkU3TP-o7w4JFSzYaFx9rdZxlKEOJG',
            'four_seasons_hotel_abu_dhabi' => '1Y6wlLcy4anWeFchG0XCn6FXGagUJxyac',
            'four_seasons_resort_dubai_at_jumeirah_beach' => '1x8mb0MJXWpub90ah9XdCbQJSyJZFY7fv',
            'park_hyatt_dubai' => '1YTnlDuPYvxriFRxCs-UXj_eqzeKVM_sj',
            'rosewood_abu_dhabi' => '14pC_23310jprlAz4cEErFLv4ZULEQjHY',
            'shangri_la_hotel_qaryat_al_beri' => '1swXvSEjxI_h_3IS-RJOU2gsW-sM_EbY1',
            'the_ritz_carlton_dubai' => '1wKMYZQ_rXMVJqt1gr5tinJuyod3ujUCM',
            'the_st_regis_abu_dhabi' => '1l9Q9E7OOezLerBzQVJrWL9AbFulDknB4',
        ],
        'united_kingdom' => [
            'claridges_london' => '1m9ABiz_eCBSixaFQYuzvk7797tdAyAJe',
            'corinthia_hotel_london' => '14kPUvSS0ubYcn9xtMpxOuu-GIyOPLdBg',
            'rosewood_london' => '1WFcMCPqMX4nF4MYlzSrFc_F_ndyiG7Fv',
            'shangri_la_hotel_at_the_shard' => '1jCwhSW91jaEQ5qz5aw9BldN-fcH5RQD1',
            'the_connaught_london' => '1pC-umso4lien0ZIJSH9IOFheHxUoHhiq',
            'the_dorchester_london' => '1wPf77m5d61eljhK9ducZeVMEeV2SLHbN',
            'the_langham_london' => '1BJBwm0vaht21KE-xaVz3R75iPs3WHX6T',
            'the_ned_london' => '1jmT5mdgTf8iS8SMJ3H6p-LY4qrCbO9v2',
            'the_ritz_london' => '1DChWNUvwrSoNyoQkqBMvAEzgMsRadPDW',
            'the_savoy_london' => '1FYzdoIu0aLCWkS5DkRyBm9nN3dve_fck',
        ],
        'usa' => [
            'four_seasons_hotel_new_york' => '1lU-s-Rrsinhq4apkk5Fw3ol_J2zdTG1q',
            'the_carlyle_new_york' => '1C3S8c8GD_4NK51V5Nt0ejf1kkiI9sfOf',
            'the_greenwich_hotel' => '1GAXHI5CzMIYIpUYJJYxAGp6jm0mQrYCe',
            'the_lowell_new_york' => '1iIDayBqcEvbn6grWhlicjioPDxayG3pR',
            'the_mark_new_york' => '1fgxiNsS2RbWQIR2TWlJOqXdINDIf3LRK',
            'the_pierre_new_york' => '1ZZzxEuHh2g5hpJ-xDYPtUQNbSQcwX6fX',
            'the_plaza_new_york' => '1idjG1Rqoy7r662KLu11clnLYHhP05JV3',
            'the_ritz_carlton_new_york' => '1Mh2N2VLJKtCJJPUoViJ4nWvgfj34UT38',
            'the_sherry_netherland' => '1gbBxlqKeLt4INVsWxGL8814vf04-_YaG',
            'the_st_regis_new_york' => '1jgccwvyOyArluoRYP2O4d8eMzi47qoG0',
        ],
    ],

    'rooms' => [
        'australia' => [
            'como_the_treasury_perth' => [
                'room_1' => '15qaRB1IXneYIhfiT50N-BKeNOue624pf',
                'room_2' => '19fWYApwCwnGJbYNv4JouzBD3cI4qEx74',
                'room_3' => '16yp8CcKZ6wNe6VRVUoYCmCb6WqJByxD6',
                'room_4' => '1E7xHCoVk_cESTjnPknktvB_vtgQEarRN',
                'room_5' => '1Dt42-TZfZw8vpev4a5Gf03IftJB1EYXA',
            ],
            'crown_towers_melbourne' => [
                'room_1' => '1YHnHErr4gDbhc1ru0QgQsYS0lbhkzxYk',
                'room_2' => '1LIPrFCgEZ1VzKP6j_V62STyHFD4lKoND',
                'room_3' => '1ngS6Ltne0-ZbpBO7yr6iutWT6ih_tIUX',
                'room_4' => '1Y0z-QLtA1dE6NfTUamODai-Vp7gI9Ghj',
                'room_5' => '1g5-Iby8abivmAIJ8nz-YxiOLLds9vEvo',
            ],
            'emporium_hotel_south_bank_brisbane' => [
                'room_1' => '1CIo88cEwJq7I8__0zU1Z2FD50eB6rBNw',
                'room_2' => '1w2E4bqTE5VsLcXNoM5whTHdFZOtUUcT_',
                'room_3' => '1C-AYWEvltq06NIVBKnSchbZLdBVCgWwy',
                'room_4' => '1Vxbm2hkJ0minrtgdmxeyfdCLxJUeA2tZ',
                'room_5' => '1MaWrnyWx13XsKfjb1vx42TzNi36-OXyx',
            ],
            'four_seasons_hotel_sydney' => [
                'room_1' => '16cQSkioU9RUpP2IPYIqYLsH-APLfr57F',
                'room_2' => '1cuMSw9y2xoLG33fE0lBZenYJ7vkY_Hmk',
                'room_3' => '1HZ0VZLbGxmsmddrFt_qeHEUNLU7KgtuC',
                'room_4' => '1QeBx-4hFgMsMa6bex8t9Wuv42TFlkH6-',
                'room_5' => '1hyZUmvzL_TtflolBYOKGvE1jgtduQ0GY',
            ],
            'park_hyatt_melbourne' => [
                'room_1' => '1W6IJQVwnYLCS2YBqf83HSqZyapJ_y6gz',
                'room_2' => '19HmT8YipkRn3j0dR1BZKLO5Pdo0IHW3H',
                'room_3' => '13eV8br3lGhFLerMqc6h7SvHPD1lsdYek',
                'room_4' => '1FAvvtoQ1nC_0soVVgXiqgLx8eco_tO4p',
                'room_5' => '1Hj5pu6NjDqm83ORbuckrz0_kG89AxImr',
            ],
            'park_hyatt_sydney' => [
                'room_1' => '1kEtVrAIyujSeEPyvWorjWhnr0iBiQHzF',
                'room_2' => '1nPu-Qi9fQJcZNVmtCsgPopJy8k7Kq5YD',
                'room_3' => '1m__YcJhb-2E8u1cCe8dGe1tj7DRdij3Y',
                'room_4' => '1oD1BwJZBCHLpIspMkBhChVD__iDYdXA8',
                'room_5' => '1O-hab1V3QQspZTfYzF3rUTaPLvXys2Lv',
            ],
            'shangri_la_hotel_sydney' => [
                'room_1' => '1zJDDTn02fWIJtT47u9TvveOVw8BPnJIY',
                'room_2' => '1mt8pWtwCG6sXt3K7vRnwqJpbq4Rovm8T',
                'room_3' => '1AM-g0SsBHchLPabJv5Kz206zRGUmEaAU',
                'room_4' => '1zEi3HqRk9d2HY7HNmtTC5wjvbwvsVY4l',
                'room_5' => '1KmiarxDRXTXLOTHu8bMv-iUHn8aomC_9',
            ],
            'the_calile_hotel_brisbane' => [
                'room_1' => '1UdeexLHGSt8Fnza-pYL3btQkSlrdBrd-',
                'room_2' => '1BRi6m-RVqz1D-Fd_AWM6gEpWYssD--gn',
                'room_3' => '1gxR9XPk-jmnL9TTnxy9EX2A6E4zMs0mB',
                'room_4' => '1tMMEYSUSc0vr7MNWLhR2YtIOGGNMEyjs',
                'room_5' => '199FSpi8VUhqEkrtIhZTlri3RanRyZUPI',
            ],
            'the_langham_melbourne' => [
                'room_1' => '1rMrOOE7qONKWegc8rvoes1DRWBcANFEw',
                'room_2' => '1gL8cKMEI63DmFSwwH0TOcQA3tEVH4vJK',
                'room_3' => '125qzsxgcu3Y9otjPLa1x0Df9oaj991SZ',
                'room_4' => '12g99ThNEGAHBx5c-KPAcwu9dVQp0J-Sz',
                'room_5' => '1BtRAW4meGq0vqvIhHj7YW-nNmWQMZtOl',
            ],
            'the_langham_sydney' => [
                'room_1' => '1T65u2-45oCNXNvYmV1bWFMvkRHwWcBej',
                'room_2' => '1Ucg96_yfA1SdNX2S_EeHEXLCZy4Zkz6X',
                'room_3' => '1yCnRAip-JGM1AaTxC42b5VWDWx5iAal3',
                'room_4' => '1NjGQZsyVqD-PgrIjKx4KPc4FIeIMWjH8',
                'room_5' => '1wh_5KjuJ8Wxr_KDeLTyfK3KuWNgVSUX1',
            ],
        ],
        'brazil' => [
            'copacabana_palace_rio_de_janeiro' => [
                'room_1' => '1t7_J7Tu54GNvuXOwhlarS3WPOyXgkVxl',
                'room_2' => '15QsBY8L-em3gwSYZy6OS0FmcEL9kqeqj',
                'room_3' => '1XojcOn76vQGz0ybn34DMOHi8z4a_DTKm',
                'room_4' => '1z6K5eWvI2SyruBoVqSFdn9P16Zxo6pQd',
                'room_5' => '1G9dbqXWUv_-5Vf4DhqcYLRFh4vpT4iul',
            ],
            'fairmont_rio_de_janeiro_copacabana' => [
                'room_1' => '1HFO7nLUh7EaibUBHJSxovFwq_PClSxvY',
                'room_2' => '1xgwTzvMUDlUNu_lFPf-c6mjMLfAoqkDU',
                'room_3' => '1eXQrOvpC3SpSYtvVwSBbA-s3iG6uQgbd',
                'room_4' => '1MsCJYyBuBMqwl2xQAMqAbCyzIw2Q8bbb',
                'room_5' => '1W7Eo1aSEEQvXQNFtoZemcNBl-g0Kzqna',
            ],
            'fasano_hotel_rio_de_janeiro' => [
                'room_1' => '1tuwYW1DoNpSyxkSdsVQ-O4v10EBoc1V8',
                'room_2' => '17E7GUWjKjCPtSICPvGpHGVWuthktc0Pr',
                'room_3' => '10UknT7rRfM0HcRITIMOdLQ1v5fJQ7DUL',
                'room_4' => '1kM9FtrUgfZfnJX9a96dJrFWFU24KioX8',
                'room_5' => '1CNXPevpvU0dem8SrYBQBu5RCcEt5O-pd',
            ],
            'fasano_são_paulo' => [
                'room_1' => '1OOYZKUzEdrrlMLGI64mFFPv7zo4Lh5mt',
                'room_2' => '1sK5hdoeu09MYPMnJrJe9BB06_2CuMN_7',
                'room_3' => '15rpTc-GtH2oksnGfpg5kUjnTJL3CbgSC',
                'room_4' => '1ZqE4uqhzkxDCOU9tTDpHquEVt0qzL_gu',
                'room_5' => '1PHUi63dlrsYWKBiwc_fuBOoqv1p9_NqY',
            ],
            'grand_hyatt_são_paulo' => [
                'room_1' => '1kS3xb6S9sdDEj27OWNDZxpuBy4ESIDcZ',
                'room_2' => '12svryMJulTi4lBGLg-5VXLvWhq3y1ZYn',
                'room_3' => '12BqvsvrbKDUzF_Ga4Y6Dz6S8WNQxgxGt',
                'room_4' => '1jMVL91WJThfiT8divmwMu3m0gLutOsJB',
                'room_5' => '1VqxSou2YuR18DuLTXqGrVRWADKvSr3Tt',
            ],
            'hotel_emiliano_são_paulo' => [
                'room_1' => '1BHC-Ct3KvO0Jac0oPr8EMzGOp6Z6yoeG',
                'room_2' => '19EfEhWawJezJg9Zqez5Ow9lwIvNBJfN-',
                'room_3' => '1qfLsXCihLI0tgCulRDg_s0AQlsPfT2G3',
                'room_4' => '1F-hUs6x6Pr_Yt4pMnQScvRW5dR5Fbq8i',
                'room_5' => '1K2Bpt5hVDPFjbMkKBJQHMdRQbJjfpmwX',
            ],
            'hotel_fasano_boa_vista' => [
                'room_1' => '1fWwuxwla7JUehR-QgtD4FT5hRr2MSnwf',
                'room_2' => '1_r5tz6p2Yc3tWav4_0t7S48Qwx_KcoEI',
                'room_3' => '1Cw7qza0VNdbL9HYL5fQUABZUnoc84ftS',
                'room_4' => '1otmxAA2xrBx4xIGi8a4IqQMpjp9JnVp2',
                'room_5' => '1dWw6-ebB4YcIkj6uPFIGqxLi0EkP5X25',
            ],
            'hotel_unique_são_paulo' => [
                'room_1' => '1yoXWNWUYzuZGkWAe6ZSaa3JOSR1BawVx',
                'room_2' => '1Xw7uU4Kor-r_knAQfyWJQKsa9027b7Fx',
                'room_3' => '173m2C2F8WJsancPyVoyusw-btuKG56hi',
                'room_4' => '1PtEuiqRhicy9C8yTeNm15YYieeFmtvuU',
                'room_5' => '1onfruJQ8TTHxEPnqgMxEQ6XXmTNsdf29',
            ],
            'jw_marriott_hotel_rio_de_janeiro' => [
                'room_1' => '1ocP_XxNsugnQS9hi_YIf0wjChoeaMhYv',
                'room_2' => '1-yM4jKe072JlYTGoGABjyV9yyS-Myn39',
                'room_3' => '17XnIA99ctglHnjTicwBMCvCSMeC6l1sD',
                'room_4' => '1X6f0__Kjb9vYwwjKiIicOlAcaRDSXC_L',
                'room_5' => '1WlXADHOHu2BW8vK3ZOQizaGcCNYs8phT',
            ],
            'rosewood_são_paulo' => [
                'room_1' => '1_hKrlyiRNuacUr8ABPJrxirDrp6Q2NZ5',
                'room_2' => '1aRCI4377cMxE0bjlWynpiQ5E6fkh-UcI',
                'room_3' => '1gz3_NyDJLhHH8LZRcgVDH8xh9z6Oc0fQ',
                'room_4' => '1MjTVdM8w0e52IhEK8oZgf41ENNyHCrRI',
                'room_5' => '1TQG_GazPhAkkV8BGqxAgnxUTlBrRB_26',
            ],
        ],
        'canada' => [
            'château_frontenac_quebec_city' => [
                'room_1' => '1rTBJMsvP9KvknXzHpGxXhIQ1Ww1jcZU4',
                'room_2' => '10WJbZi2qyEUpbYdI_KqxKtn95LUScB6E',
                'room_3' => '1nUeo7vW_0D8BwRndmgTmi4R6iacxVoxo',
                'room_4' => '1UNUuVSG1oE7xEU2zOp2uSgcM_3EiEtQU',
                'room_5' => '1o2Se8R-2PAPJ9kfjtMCh-WFvR87PEGlm',
            ],
            'fairmont_chateau_lake_louise' => [
                'room_1' => '1qlkNHoWYsOqIumhrvzFLbxdnIkcDPOA1',
                'room_2' => '18Q8OokUaZTzA98yQLAM1fTQJp7cQoSQW',
                'room_3' => '1OVtTwVU97gcZDy_mm8dZMI3HGrKRiONj',
                'room_4' => '1HqwGP309bLHUuCzzpWJ1pb_93IN5JurK',
                'room_5' => '19yJPhxxTW9Qwrotj84YHnp7AQX1UZbwK',
            ],
            'fairmont_hotel_vancouver' => [
                'room_1' => '1wYOdnm1uZST5fTuDSeGIpojKnBGA19h4',
                'room_2' => '1RVVQ5uhbcHCGZ_hQUJw87lFwgzeo7SLt',
                'room_3' => '1gTmIyPi63dhjHxAAT_QiEJnMtz9JbVC_',
                'room_4' => '1KG6llZu0-tjbONOTsT3zmSgLvep6cuBB',
                'room_5' => '1Vwdl5wcULnwY973lU8OuQrp4SLB1ZoU8',
            ],
            'fairmont_royal_york_toronto' => [
                'room_1' => '1H4WwSRZDV2vdJrVKk5XgkgbFyLcjw_O9',
                'room_2' => '1CzXeM9Tt4Ri8yoGsK7YgXLbiZU3aYqRy',
                'room_3' => '1ZlLH8t34Otzbc1K-fNhqB3NimlN3Zfpg',
                'room_4' => '1ndBTDzt_uZBnOmpZ5Q-vXNaL5_K8XfSq',
                'room_5' => '1whLNX3T96E-A1w5cfhlC2fOVeEmFhIEn',
            ],
            'four_seasons_hotel_montreal' => [
                'room_1' => '1Z4kFxa-4vOiQuHuXmaUsGH0DUjY4Y1RL',
                'room_2' => '1orOwDyBwKf4tx9RZ5-MluMYrBuYdJ8rS',
                'room_3' => '1hk7Fe3eWXZHd2jy4F_rvR9IPMgoWKuI-',
                'room_4' => '1mebBwYaD4mq-_XrJ0R_qL7yOA3-dMX0y',
                'room_5' => '1soV1jc5yGNl9Xb25kzETXnciphQxXMmy',
            ],
            'four_seasons_hotel_toronto' => [
                'room_1' => '1s4uYv86Zla0Tqh2lPUByfOXcn83GHirh',
                'room_2' => '1lFNJ9K1lA6E_ehO_JtvgCucVIwRn2dop',
                'room_3' => '1hvt9lGFogfInxwseXHijpPbNWV5iUl7V',
                'room_4' => '1PPdzHrH-SquCLWuikDwTZQs7LhN6hIoi',
                'room_5' => '1HDSwyjqiY-kFx4T4tinjQeuZk1oXr-DN',
            ],
            'four_seasons_hotel_vancouver' => [
                'room_1' => '1qt9-4nQ-ADbVLQ_hiS7mJ-FgcnKWfp_V',
                'room_2' => '12o4SSYWDYfIp_oV72cV_PkCwFYsLEJLw',
                'room_3' => '1zetYR1wAik16hnyTnVK2SteIr7fay6gR',
                'room_4' => '1c-_9QYAfPBAum-S7NpLTet7SGECV5AAK',
                'room_5' => '1osYjQeiwBTyl91lnoDOcTkkaO6RyGz-b',
            ],
            'rosewood_hotel_georgia_vancouver' => [
                'room_1' => '1fs8UpCwnEIFBxWX9Z1CUgMfAfHV_jdBZ',
                'room_2' => '1cAYmipcuBkwhta9T0gFkeQfnlnS2tSlE',
                'room_3' => '1l6mfBEsfTlBdCd1t6N8ZrWGObHKFndfB',
                'room_4' => '1LY0JZiRvk2miZVNBYf2_bpnemRT2DaOL',
                'room_5' => '1LoxdYsyaF3WQG4dlvLuG3tekSg6kkpuk',
            ],
            'the_ritz_carlton_montreal' => [
                'room_1' => '13D1XcSmNfOhn-Vbd0URnJwXuF97yuDfy',
                'room_2' => '1HocymZuOALtCRAbg2yU6fbvf0CDtSysn',
                'room_3' => '19cs_psu0nti9GrXwtOo3RKRcxSHfMsHq',
                'room_4' => '1Aas7J4eEBuOWnoMk3cokiYv2wv-6gKhW',
                'room_5' => '1waTcMYK1NeqBDe-Xk5Ri768TzAGMUkZE',
            ],
            'the_ritz_carlton_toronto' => [
                'room_1' => '1cWn6arQBsqLo7tQCuuQcqCtU4UJs6iiR',
                'room_2' => '1E3HC2Jo0LlAa-rx-5oDoPrLkMmfE-n_X',
                'room_3' => '1q1EEZUZmMnCyc0K5MX0leyL-6jZ47sGE',
                'room_4' => '1487-gaRCzKZMVNsPhbdDmGUUtAM4rkME',
                'room_5' => '1MQiLqvApW_A-ZEiv7bvLxbucEZH954J2',
            ],
        ],
        'china' => [
            'four_seasons_hotel_beijing' => [
                'room_1' => '1ixk1cj8I-k9D1sOCGG9VbmWHeDAz2tjR',
                'room_2' => '1rRIrBK0MCrA1aQWwMG-6G48LFozpMrot',
                'room_3' => '1TPugRr_aTZy0pB9eekYUE8H6_z4lQ1f0',
                'room_4' => '1CBwS23mvFMjcCQz3aqXc7MXDOskYqojs',
                'room_5' => '1yII-G-tpGropisEGRvICB1ep8SxPq8S-',
            ],
            'grand_hyatt_beijing' => [
                'room_1' => '1O_jLLxo54AKqvJFozGecazpolVGz2oS1',
                'room_2' => '1O0gN2vynoxILRjHI6BOxjzvVwlIucmhO',
                'room_3' => '1fZRLra8j9cpzWJe5dMGdK4WtJpX54iNS',
                'room_4' => '1jxhWaOeHgsnjPzoGwUClr72l4XbsW-Zu',
                'room_5' => '1kXOsBGDB1HyXTXy4k7M-bxFJOs2cKjgQ',
            ],
            'nuo_hotel_beijing' => [
                'room_1' => '1LOzkMGzQncrqk8PMrsx7JxBHeOwnYQFT',
                'room_2' => '1OYtIVpUtUjsgsXcgF1Z4XjZF2E0RMGbT',
                'room_3' => '1UZ_q4AInbJQqyMdtCXlRDOBJPWL__wZX',
                'room_4' => '1Idd9slcs-L9YXBEotttCGY_CkhQyiAiE',
                'room_5' => '1Rqpz3PUJtO0CaBysRnUCxtxBOhyGHPSu',
            ],
            'park_hyatt_beijing' => [
                'room_1' => '10fN2aGg1xSf1hrd5Pdqo-aETb9pmDrBN',
                'room_2' => '1HDZN6wFR0Q--N_ISS3DIfL-JNMM4ZGX4',
                'room_3' => '1lUluNTt0sXt-T2dvuFEskr2l0TCzxAFZ',
                'room_4' => '1rohSAsrD3M3TzrftW8tIHjv5JdRurRZZ',
                'room_5' => '1ShEMfsObZJyy7ucVZI1v28oxWhK5iw3C',
            ],
            'rosewood_beijing' => [
                'room_1' => '1y3sixCxbeUrxOyEVDM2alDOlQB3EE3Ff',
                'room_2' => '1ITLdzYSerzsI8U2iIH6ogvYLAx8IB1Az',
                'room_3' => '1UFhsr_Obbgvmb3PlsWTbZBhGwlyA6wh0',
                'room_4' => '1teiXXgEvqDdvqqog_Ge1iit5jyQM1nqk',
                'room_5' => '1SAMVXSF4ClhVsXJP8ey8eA_XoxBGljsv',
            ],
            'shangri_la_hotel_beijing' => [
                'room_1' => '1rAbxFdieAvVzxvXMvx2eCJV1Tlsu-CSu',
                'room_2' => '1xIkUd1eCOVRfSwQo0DErsXrbA3Ix8Kd7',
                'room_3' => '1QEbgjfQ2L68ndiUmzNFHHfJ-mHEjWXS1',
                'room_4' => '1F0KjrlEcn2rosPsg1KL4TuaO2W5CKBXC',
                'room_5' => '1abnFvZu4EmEHqniwJbSa7EtHmXsSjrwm',
            ],
            'the_opposite_house_beijing' => [
                'room_1' => '1YMkWo_UPGI8K9puvc7OukQhz7VHlj8jc',
                'room_2' => '18aanK7DxC1XJ5wCocINvqygwAPFmlaaZ',
                'room_3' => '1jmi8Xl7WpaEuCLakehs7F9d7UZgW8nbN',
                'room_4' => '1jGku8sopDk7Qot5RPWu9u6FMwZ1WFMzf',
                'room_5' => '1DFSbvTAi4OZ5CO-VV9u4OyrLScz4BtJj',
            ],
            'the_peninsula_beijing' => [
                'room_1' => '18xaqn9Ch7vp9q5Uj1xraZn2-k0x_s_zc',
                'room_2' => '1pOrs0Zdc9UYfqRO7iFKufubgDJJSp7_7',
                'room_3' => '1c-Ntf-8NAJjxqvVrJ2lz0yo0DFMZnPtX',
                'room_4' => '1QnZOmw-PAj8v5hWWiFPNBGeN3umtwUI7',
                'room_5' => '1MfzPF8yQxMcu2Jqb0zgndp3Dpzityajc',
            ],
            'the_ritz_carlton_beijing' => [
                'room_1' => '1t-ADRDGPnoOlrQU4AJaVPQgwMV3B10KU',
                'room_2' => '1Pd9J_4KhNI06AioEgERLBS4fQYiqSDAz',
                'room_3' => '1WsTkUQGW0_dX1ZXpEQ0BzG2Je3QNN3UL',
                'room_4' => '1oELpJ14ryQq8ki3X3w5mqXIY5jH_0iHv',
                'room_5' => '1waPxR3nkzHf5d5NyNoosXn841QLhn5nX',
            ],
            'the_st_regis_beijing' => [
                'room_1' => '1KmRyAPB-eVbttAPgyKGAhA0iKG881Fnq',
                'room_2' => '1x17vrzrV74XsHMMMlq0rpoyX_2BXUOqg',
                'room_3' => '1xNJrZmd1On_GarKLOHEICYj5XWJtPl4e',
                'room_4' => '1d1F3NJA0oCSH-5Imk8sErG8anLRx57BJ',
                'room_5' => '1UOxcetqwoXH4N7838FqwTJ1Tmaaitmod',
            ],
        ],
        'india' => [
            'itc_grand_chola_chennai' => [
                'room_1' => '1xakfgKYF6ojnoHXxP2kzMU6UYPeP6FXk',
                'room_2' => '1klI-Brb2ZPczWfSjGb06XnbyNvZ7JUPq',
                'room_3' => '1CowltZRjRJl2QcPUWz1Ht2qt7NQB-yHC',
                'room_4' => '1Pcb95xIBeVMbeOjhMW7tWmp-_L8vyGbd',
                'room_5' => '1G9NfK-2ZHQYJLm36udrhYhEIdsHloWvy',
            ],
            'four_seasons_hotel_mumbai' => [
                'room_1' => '1ys9iRrhL4nRnLFAK2P6LccMbcRlYnew_',
                'room_2' => '1ioG5PmdYWb7PWvEE8ll0m-0FMAcTgtUw',
                'room_3' => '1uKP3UBMrI5zu_t7gyAfbOb6hOIKEkBkz',
                'room_4' => '1s_rqJ8MiDHRyIQhDBGZppNQlv5ThEAm4',
                'room_5' => '1JrcRnxqV31Y9QdbzLtPRSuddEfYEI0q1',
            ],
            'rambagh_palace_jaipur' => [
                'room_1' => '1jGUHaqc9GWZ4vT5BLHEY0qZizYesMiYR',
                'room_2' => '1o1f4r2AZ4NNuCwKdu-z-tsocCoZHif1K',
                'room_3' => '1KYn413otDc21wJL-ng4HCFIz5J6pMQwy',
                'room_4' => '1BimNYgpWdu86mbMdTa3tKoz78FMl7lJl',
                'room_5' => '1dt1wsRRp7NJ_iop0LVKnRZ05W4CIwfKA',
            ],
            'the_oberoi_mumbai' => [
                'room_1' => '1vu1vk-Oh6pGhZemA9FYeUnAm4iDqzmPr',
                'room_2' => '1JnBOo4Ll4TuEgqA_daDAT8VTIyZ5H82q',
                'room_3' => '1p3Bf9wfX3aIDPTSt5AlqsxImI863GKWS',
                'room_4' => '1s46JhE29O3ZiR0DhxQnwUOZZRhz2prcc',
                'room_5' => '1dn4XZLi6Z4fSSmaAmFsWWOtLyEkuBaC4',
            ],
            'the_leela_palace_udaipur' => [
                'room_1' => '1Wq8tCDXgSbMNsxSvZnyYg-MnfpZwQhJq',
                'room_2' => '1e17APNONj6Yub4BMfsXR31hTPR5fLNur',
                'room_3' => '1EKRiYPt7qQhntTtPO6yyAEXugs2GIBDt',
                'room_4' => '1qh1J7uwg9cPTaE2SNJ5b3cl3mcPnRTEE',
                'room_5' => '1DKq97yPraDgCPuPR3Q0wswi82PNjB3cJ',
            ],
            'taj_lake_palace_udaipur' => [
                'room_1' => '1En2yoLCgMdp2fGJGFG9ep_WSZKErIbY0',
                'room_2' => '1qAFl0YTcqcaJ-65pdTG1Z1p9102Aq8DE',
                'room_3' => '1jUnJrico4G-7fZa6i35pfrsM5GVfjFPl',
                'room_4' => '1KcJ8PZu6h4RdZ0U-ZU34_NF4t3Pvbrec',
                'room_5' => '1966SHYiYEp7TJ66pmIF4Nrbv5EyHqmQp',
            ],
            'the_leela_palace_new_delhi' => [
                'room_1' => '1znfnPWj0H2f15mRVR0KOxDDuHEoW6W3O',
                'room_2' => '1Fdfh1-xLosNQ3ZX4A06PkS_9oQmtnzPZ',
                'room_3' => '1CYZexbUZG3SugFAN1lMip3eMqsbIBw5q',
                'room_4' => '1lcacccLPRZexw73M4N2E-IP9mNkcbn_z',
                'room_5' => '1yf5dAXM-DnS-B_hLncQIqGjHfvZvfUsD',
            ],
            'taj_mahal_palace_mumbai' => [
                'room_1' => '1JWCBnaA3v_ojR6Rb69zMSTqI0Bo-5enH',
                'room_2' => '1C_8BC7mFAiBoQOUKyk15h_DAEzWodRd9',
                'room_3' => '1YDTeyvK0odRe8Lugoun-QDHzubK4fRQB',
                'room_4' => '1mU37lZrvyiU-fl-r5NcuBbbIhfNTIv7m',
                'room_5' => '1n_a8MO9373rb3cUrpRFzRqMkJ7Ol951i',
            ],
            'the_oberoi_new_delhi' => [
                'room_1' => '1vJWo__eKXrbk4p0NnKEfjUKQEUaQDeCX',
                'room_2' => '1PcnFSTf8vKW15RO2IrrCw-zf9xcIUIHO',
                'room_3' => '1EMDWdtC_F6qJQZB08Mw3y6FTzUd8QhIr',
                'room_4' => '1BT0kxfcxekFhSPx1s4J-nXZlfLRptlVa',
                'room_5' => '1gRctrRvUX5p48hPYd5ZlSnfJIYWv4xeY',
            ],
            'the_oberoi_rajvilas_jaipur' => [
                'room_1' => '1HDJ6zjdwrvqwb6ytDdgYTvSejWpOqATh',
                'room_2' => '1vOh7zJCF4sAgMa2EUlISpTlWIt49KkNE',
                'room_3' => '1x1E4dbpVDEkGwJpzFQDcsPVM51saL6BY',
                'room_4' => '1hIeQDG8pf2uTz7Cl2WTifU65JvS0Zj2l',
                'room_5' => '1m4P1C8KtezuEKkNOPb0ReQPhyySAfLMN',
            ],
        ],
        'france' => [
            'four_seasons_hotel_george_v' => [
                'room_1' => '1j2qhTiENryLpOEd-7Q9Eg7O4mdZew5Uo',
                'room_2' => '14UhxcD6DMv5qV94NbSiG96uSvlaabCYd',
                'room_3' => '1V-IhfMQJ_8XziHACa-9nS436PBNj8Npp',
                'room_4' => '1mBr7On1PMsWFFzSvBpuEpWRzg_nELpH0',
                'room_5' => '1eseNNwguUQJzq5QPSSMRyJQi7qT89SsO',
            ],
            'hotel_de_crillon' => [
                'room_1' => '1V54yQgvmK_Aq4CrMfoaldgNgZiOnYLtV',
                'room_2' => '11ue18b489X5GNG0bQlquoInW-QhemmPJ',
                'room_3' => '1kUUof9jrOiGMCmZEmhLTkdcTjXkTS82I',
                'room_4' => '1-zyXyMH9KMd7xa0L56ZtQrbX0yWtRrcJ',
                'room_5' => '16cGF2yhMLAYyjKaRYuN_hcj_flbfUR7o',
            ],
            'hotel_lutetia' => [
                'room_1' => '1BF0pMJK2lGqamzgkNWPYq6TQ0s8MIk6r',
                'room_2' => '1zKOu5W7TzL7c-ZzECT38JQ6qYYj8Tax7',
                'room_3' => '1r-MT1TlOaoz7ICqvLlVlDgzyyRd0SDJc',
                'room_4' => '1jv_hxLvm82YYoWYz2DBGNV9Ueq0B8Uya',
                'room_5' => '1SGVUSok3BAcGpMoh17rmkkQXL7HE8r6u',
            ],
            'hotel_plaza_athénée' => [
                'room_1' => '1KUpZkTsayhNxaXACHisw3SwBRh8inuNc',
                'room_2' => '1Lnf0gWetv4EXEQgoxAXLXptltSoQzl9F',
                'room_3' => '1-irUo_rWtnex_iqdBcIy8QHFq5l5ggEp',
                'room_4' => '1j297EDMQBEcbECkhepmQmXIlkzf6gD5H',
                'room_5' => '18dYcPAGBB_O4V_zwniZXjNyf0WCyFYlN',
            ],
            'la_réserve_paris' => [
                'room_1' => '1HY0-VxU_gda2RiP9RTsDTBGvQRypFpDW',
                'room_2' => '1rdp5N_rDYz5yFBu9k8cdJoz_fDJkM0bB',
                'room_3' => '1lNS81vu5LFlUhrwHDnWit7XF0h9UJM5P',
                'room_4' => '1Q1RJrzPCtHELE9KhO9225ZogrlUDanFu',
                'room_5' => '14sitq6Jh0jvxTmD8RwEMRhjRK_fU5tPi',
            ],
            'le_bristol_paris' => [
                'room_1' => '1RcTZjweHhwm-_KOsDsSTWUMuQG5ffUqE',
                'room_2' => '1KHNjv_Zjh_GW791MAFhyU9OP3ReHYQjn',
                'room_3' => '1o3VQjchlULOSKzdys0eDwL-Ea9Ws74u9',
                'room_4' => '1TePAvJSrN8MihMTZRlMnifhkj-gWjHBR',
                'room_5' => '1QpepN5rOEHHfDzoCnMg1GLXrzaCvgumo',
            ],
            'le_meurice' => [
                'room_1' => '1hztcL3pIeuyVFYojzPig8MIjs2RpKTZV',
                'room_2' => '1PxWInjY-TZ7eUgVwr986cm0E3_wg8LKp',
                'room_3' => '1xrOufXPc356X6xIGaGa-w_5A3mUEB8QW',
                'room_4' => '1IlPTkA0aN_H_Yh46KU0Hk1UVFTPD3EYw',
                'room_5' => '1vcienOygyT2034xhV85-PWdVlqMFaP1L',
            ],
            'park_hyatt_paris_vendôme' => [
                'room_1' => '1LFY2IOw9Ka0kpuhaue9DIG_A2niMl4NP',
                'room_2' => '10GlXSPpNNh-HwjLFQRZZ4DFqnawXjHdv',
                'room_3' => '1cFgfI-YPundQRxMM4haPo9HB65EMQIkZ',
                'room_4' => '1vtl5IwQMO40NT7l7I0_OBIk_fYfEJkfS',
                'room_5' => '1Y4B7zYEKwp3C5atDJgcZxg92MnNkbwyR',
            ],
            'shangri_la_hotel_paris' => [
                'room_1' => '1GL9vySe7-2oO9EijTqdgtxaH1lP0hpn7',
                'room_2' => '1tqchFpAoEGExNn_yzvDI_iuGsAqmyKSh',
                'room_3' => '1vwCrG3zVKSEhNjXkV0toJbPW95UT4BQE',
                'room_4' => '1EbqvdwkYKn9-lTGmSfCGuqeQ_5qrxyq0',
                'room_5' => '1LKNsdq3R0LEEw20_QboX-BlOVLi35mKi',
            ],
            'the_ritz_paris' => [
                'room_1' => '10Xo5BC-rIKsnjmpJ3NT5g-jcW8T5c2-p',
                'room_2' => '18t56IYXX7uX3k-IOTCKxrCeZnRI3rchc',
                'room_3' => '117MrhdkR2Etxxv6hq1BM8MJDq18GcP5d',
                'room_4' => '1rVeWcHbTBj95scW6wdszD77GWVGovGdK',
                'room_5' => '1qNeAbQpNA0ZuDSgs4fiwdgzp9pLHk8vC',
            ],
        ],
        'germany' => [
            'das_stue_berlin' => [
                'room_1' => '1b49LRZXCkpaJUq62-3EmLNLoX5oylgHf',
                'room_2' => '1jznzmreX9UN-ShdiDg1ZxFJ54NOwIqez',
                'room_3' => '1gW3AbvAoMI0Shi1ZwqmdycnJxi2eK-M5',
                'room_4' => '1Gya-Qdv1OiFxsISXPrQfn_xjq4hnCaAh',
                'room_5' => '1WiDYjwRTvvQyWbcGdP3nZKnCMgaK_GN8',
            ],
            'grand_hyatt_berlin' => [
                'room_1' => '1M9OZq4HJ_GnZIfSCEuKvgLZXlywBv0X2',
                'room_2' => '1hL5W3FIjs_zr3xuI_Lzwrb5TFbdKkbVg',
                'room_3' => '1AN0j-iVMhjcGEBE6cDrUO-BrsJpUita3',
                'room_4' => '1qzo29-XqAaWaHVLytXKcOfEl4HQLegDp',
                'room_5' => '1GqMt0oWWsaX5qW8dKZF4Z7duJ5ZrLRa2',
            ],
            'hotel_adlon_kempinski_berlin' => [
                'room_1' => '1pVXSnigLDGK3iy-qgW3uUfYaQEDb-NSH',
                'room_2' => '1RjoWtAonNkmOkTXpwRWJSsuID_i72-kr',
                'room_3' => '18m7vlr4ITPFrKg0A-l2YXTx2ueVUQHL_',
                'room_4' => '1co7aacoUsq7Y8CdsKnii2NYOVquB756C',
                'room_5' => '1kpqqtQgl2tQE6ky7x7aLnFeqpj5ecFjb',
            ],
            'hotel_brandenburger_hof' => [
                'room_1' => '1Z-TqshO1YlF9riFDZw7n6SPuxVsLkzuO',
                'room_2' => '1mjk90t2WlYRVBN1Rxv56aP9pJadoRm2E',
                'room_3' => '1nPHGJeWumb17Q8Q8EfALqBFim1tN9ZfF',
                'room_4' => '15n61m4wNERtyVi4-p-BQwlS_Ub4n9l-o',
                'room_5' => '1BZpKxyCtABDeJvEZPiii0R1R3D50zyrL',
            ],
            'hotel_de_rome_berlin' => [
                'room_1' => '1gmGl2Bn8NYcdv4Z4nGowjIB4QJ1CECTh',
                'room_2' => '1pPEYM1cVQqP_MP4HzrLwQsW8kLR2D18m',
                'room_3' => '1O5XfGI-aCfvu7EtZcQnqazW-ympmQ8Cr',
                'room_4' => '1yPy2hvQJfwMLpsdeJ_vCWWPmk6gOhbB2',
                'room_5' => '1zB2m1cRR9MzUc-hCkOAqefSB-XajRSaQ',
            ],
            'orania_berlin' => [
                'room_1' => '1kPOSPupFm41InS1Q__0_mTi_JZ6X_yI5',
                'room_2' => '1qqVvCWEsYybQ0r51BWVo9F1oYYW3bKcF',
                'room_3' => '1HGEpb3TBJ4_0pBg6eRQrXoAHM5gbZUL4',
                'room_4' => '1ALnIYXsjlBvPlPvLFwE307-exvH1fHH4',
                'room_5' => '1jcXjV3XHr-AML6B4pGlZDp8OgilUic6j',
            ],
            'regent_berlin' => [
                'room_1' => '1NH6W9IvrzsPFB5Jc-B-KfHxm2OKmxHjw',
                'room_2' => '1an-WEoC7FMU2e9dmqUbkRLzIlDhqPYHE',
                'room_3' => '1pwBKSVWENZnZ9aeOktHjFmMt2u-GfKGx',
                'room_4' => '1kyaLxRBYumjPrjVHubxz94PaRY9ptcKa',
                'room_5' => '1uqZ9Vk5Y9fmMlCBIUCNKviAn-joU9PPD',
            ],
            'soho_house_berlin' => [
                'room_1' => '1dKu1fTh0XTLwPRWqF_b1aekgeUfm81IJ',
                'room_2' => '1TOA-fS3E_qrOiNN228Lwc6-b1XEM2hxO',
                'room_3' => '1Ngy9RKRwFAx0FROybqND0F1oYab78dIf',
                'room_4' => '1Qv0WIeGe51GhB6NUuDAJsdAudlWt8Lwf',
                'room_5' => '1cs0g2tdOxJvCHiFTmhNHE3SGSM27X69P',
            ],
            'the_ritz_carlton_berlin' => [
                'room_1' => '1GKvT-bgJQeGOVZ2_nKcm8R59q_bev9jg',
                'room_2' => '1RvXdHpLTeETkz9oc33GsFpOX0ksrExK4',
                'room_3' => '1RP9kRDmFwqWj6GWUZOkcTzeXwlKqZKIR',
                'room_4' => '1yVnIOJ3Dlnlw9H4kNj03bpwRkQjm2fsF',
                'room_5' => '1keKvj_Cgkon8s2EdXYborL8HUW2aTLY9',
            ],
            'titanic_gendarmenmarkt_berlin' => [
                'room_1' => '1cCBo3XhXxgbChAqRN_7VUj6DAbYCkr3b',
                'room_2' => '1lXgt7OhPHQVBOgnPPGZPTyM2vpp4ErWa',
                'room_3' => '118XsY8tEHvYhJylGJ3MU3Y-dN1jNk1YT',
                'room_4' => '1cmaFqQfNa2U1FJSY4EYz8ZxK-JgQN89_',
                'room_5' => '1jZNv7A41n3THSP0BY3zzJOqefYvYiNzi',
            ],
        ],
        'italy' => [
            'four_seasons_hotel_milano' => [
                'room_1' => '1iYteIfkWMUgSi8lQvNDssv5bPPpwFJQ4',
                'room_2' => '1xRwhgO4TPuEeOQFUnRkY2o2IPvRFg-SM',
                'room_3' => '1ih772UVvEu7iQR81FQnXyrEmTtpF6dDP',
                'room_4' => '1sjAg31pUEk2J_Dyf1I-AYx0FSRxFSx9z',
                'room_5' => '10YgDdH4PrCQlQzIrZWiDRkrpoDM--h8p',
            ],
            'belmond_hotel_caruso' => [
                'room_1' => '1F4Rr1cAPDVLFRSD3fTjPQgRRdla9MLCP',
                'room_2' => '1v4uYeG94QBK3ydor_OXJathDg91_mOS-',
                'room_3' => '18_kvlVVIdJzjP7KNd6na1OIW-QSX4wXM',
                'room_4' => '1U5t6OC_SWFb23jrm-iAjQGqvx0edEse1',
                'room_5' => '1QSb-GYO7BGgUoEmBPdHRK-5JtLXM97E8',
            ],
            'hotel_de_russie_rome' => [
                'room_1' => '1yg9AbTX-anthXe7PAfHwIHJfiaTT3_BQ',
                'room_2' => '16vkBajTwFF-ZGNWPXhtxJxusnFM-xXWA',
                'room_3' => '1n60QxPHxcxyci7cPzjVgRPds0ECwUnyP',
                'room_4' => '1LWMlxT-4Q7uGhl8CXkIcJKF_hM9GZGCP',
                'room_5' => '1unM8A_8rwBgmV1VBWrI7Mz2TQ6G88Ibz',
            ],
            'gritti_palace_venice' => [
                'room_1' => '1zJhZjUgJLYa3ZI1Gds2GexlgyccvqUet',
                'room_2' => '1FHmG03zTACt2E7TLq7tWG8NEUHWsDlFx',
                'room_3' => '1agYVBd5_p-IOW3Ya27ECOg7rFBmKFdZp',
                'room_4' => '17Z6fkvSMRAqLWnkpwoKMSjZtNVK2jDz2',
                'room_5' => '1YS43zziV4jCqIxDws6fHqK0I4zah0tEb',
            ],
            'hotel_splendido_portofino' => [
                'room_1' => '1Qytp07k6Jqe9tLzNKnpa7nUujF7sxuyu',
                'room_2' => '1Eo8A5cq6EhiKxrgnbfyVjZcLYbDPRiNX',
                'room_3' => '12vylcCVdsaFfeegbM7Cov9QD23KXyBck',
                'room_4' => '1GKB--nnGbo-6F1a6H-ApmlaMx_fdiz32',
                'room_5' => '1zY8XypqqsWOfWMT1q5Gp9WS2Ms2ByhZQ',
            ],
            'hotel_hassler_roma' => [
                'room_1' => '1rv_P52mJtPuogkqV3l5XXtHhX1KOnuiP',
                'room_2' => '1k5YdCGeRQfG4DXkAK_q1Hg2NPWaUDrx8',
                'room_3' => '1R--6rwSOcF7zQcxI5fHZSERkg387vuFD',
                'room_4' => '1M6i_xBq_bFK9NaA98P7nB3rSicZVaxBk',
                'room_5' => '1ewYQSq0zCL70d8Ip6CtP5SDpZaQODDYx',
            ],
            'villa_san_martino_martina_franca' => [
                'room_1' => '1rQSVRkHP-ugugsypt51odVFC97xS2R4d',
                'room_2' => '1k0CP32gGmKJCdl-3xhutUYHNDkriaX1P',
                'room_3' => '1_lVbxVI-NZjgrCeBIPdArO4CM88u5zgB',
                'room_4' => '1HZ3P10r8kVf5nnmy-_B_WoVnRd8bo3QN',
                'room_5' => '1qsLDF0T-Kd93JYZdIQZQ7Z7gqarQA9Uk',
            ],
            'hotel_villa_cimbrone_ravello' => [
                'room_1' => '1YsqVlIkUsM8GmNXSjOGa-apqzt8KzhUK',
                'room_2' => '1SaiqtIrMRdadQgxllRhSPN-98j9cqfxq',
                'room_3' => '1vjEqbUA-vmMQR8QY53ugUHNHUoJXMKX9',
                'room_4' => '1qb2UZGYZZx79ertbKLPm6WL9JcAecb6z',
                'room_5' => '1aibDPbZtTq4AhhMCgVsbsgdCeY9jQmmI',
            ],
            'the_st_regis_rome' => [
                'room_1' => '12c_gM5RsglTNj3W0kHvUv2QXzBcxHW_3',
                'room_2' => '1QYUXU8lvpnzUtIYJiZW0Y7m0YB3SI1bb',
                'room_3' => '1uN11dqUlBoE-4qTss6g39vEsD-ywtZnh',
                'room_4' => '1S2XA1EConAajK1Q7T5eKyoooyv5BXVs7',
                'room_5' => '1c9GMlo0ejxnjvD-m7zd2LHQoQ5grfx1w',
            ],
            'palazzo_margherita_basilicata' => [
                'room_1' => '1_dKsMGCAv9PPZufV1hh6SIoPP6ZgaNL4',
                'room_2' => '1aBQKnFYWLJ0SubpciHfp2GgpLQ4Eq3Tj',
                'room_3' => '13iK8WFaQto1-7gEVNEKmQ_7uDao4Lo3S',
                'room_4' => '19rmaj_QWlgxdAQljOMRyh7PiC9iAewAk',
                'room_5' => '1xDFVo5k4SJERkLEIgQplVgK5FHGZNi6S',
            ],
        ],
        'japan' => [
            'aman_tokyo' => [
                'room_1' => '1jDRRB_rV2JTfrSyEzkgHD6e8lVcHt0yZ',
                'room_2' => '1K684oICEXjTxXF9AEGVnDhwdfjwq9x4N',
                'room_3' => '1_IwGsVZLJgOORglNv9O_rF40z7uyW_wI',
                'room_4' => '1leMQeFquAXHc0WR5lzmEvLss-ZZIKsMF',
                'room_5' => '1KiEpjjRfiBwDwUE-hvBbhLMx6vN4rqeA',
            ],
            'four_seasons_hotel_tokyo_at_marunouchi' => [
                'room_1' => '14I1-kzRnAbYiOchaUqKBaQhTWoDULRzg',
                'room_2' => '1BWRUG7kZcGOcFZ7wi1d9ez_j2YPq3ICB',
                'room_3' => '1J8KrQY0S3R6E89EHk3Z8oyKyEQrV51yP',
                'room_4' => '1T5LblGR1jviW7iwzli-aqAiTa71bGsED',
                'room_5' => '1sLPRtZhOF_qq21V4b0AfF_xt8F2-1IB8',
            ],
            'hoshinoya_tokyo' => [
                'room_1' => '1P85nlMMEfEuWo6HSG4yN_t3TORmxSUBi',
                'room_2' => '1eFzPU0icLMX4ekO_OmSp4RUbnYU4dUsb',
                'room_3' => '1LNbdYIrCyZBMqFhCwS8vNLaT0zZ6AlkA',
                'room_4' => '1wGlBVdbKJqpvB8rzI_vohl-wNfEy-cgd',
                'room_5' => '11dMy8ZtnANc9Ko1u5xFTJfua5pQcHtfH',
            ],
            'imperial_hotel_tokyo' => [
                'room_1' => '1HEGecaTi8LAhcwswJt_0e3s4ByXUJMnZ',
                'room_2' => '1KIsZGCxue5PMHfJIwKfsOXW4TtrzlQSw',
                'room_3' => '1zKHtNV2msMccE47DbYv-zJOOZ0C8Rbs7',
                'room_4' => '1Yg7XJSLQU58hzjTIU6Q0a6Qs5uspQlDO',
                'room_5' => '1kgSOHGJE4udgJjKRiMIPFiXFLXlK8yTi',
            ],
            'mandarin_oriental_tokyo' => [
                'room_1' => '1_k2ScbxVF4OOVJbqnAx7-UjulxwEa9B6',
                'room_2' => '19s3RZP_Rl0bw_3b2lEMMjbwneECDjMmA',
                'room_3' => '1HkGdBWzRwQzTr-uKT6vyKqFEJO9RJTTO',
                'room_4' => '11Qn3cG88qPc3_cgPeV_MeDZGeIlQFwbX',
                'room_5' => '1Arsi69EFYxgBkym6S44vpuEUgQAiGlwM',
            ],
            'park_hyatt_tokyo' => [
                'room_1' => '169w1AB_kLpyk9_J_IMRh-TIzINUrdaXt',
                'room_2' => '1oWWtSjQCSJrAi8oZphW2cRpjX5Y_t9tu',
                'room_3' => '1lbdFc5LWXzAsyufKP9CDfAJQv6IAzxCc',
                'room_4' => '17B3RP7Fte77jEngAFlXqfPAdCXlZH6dO',
                'room_5' => '15gngJ21VbTfADg4x5Mz4NksEZHeJIYhe',
            ],
            'shangri_la_hotel_tokyo' => [
                'room_1' => '1zrSRN8vHugT4x0TU5sLlVS4YbRJV-51e',
                'room_2' => '1oM9KnvlYHFPcJ3JN9zyIHJ1mbi77L24C',
                'room_3' => '1hr_8iYt_BiDQwJFJs7lKQMc1jb-QtEtJ',
                'room_4' => '1O9aZmNKgXQ15K8lkPcPS1JXD1dJzUN0o',
                'room_5' => '1J9K31JbvtKxyQPwg9w1_Uw7MCWQGPZgB',
            ],
            'the_peninsula_tokyo' => [
                'room_1' => '15iIBEqWQKCJhGl2ze9eJKiees5MLvtHk',
                'room_2' => '1-jg7G55amv1Rv3W65mnRZE5Ij-I8lR9r',
                'room_3' => '1w2DhmUYlH6whOXbFPeo68mxBB41iIue5',
                'room_4' => '11zfvXCeEVJ15p-LRTPe6vpvdZl-LwWGA',
                'room_5' => '1vPVEYsITYt8_mcCuumOMxBNWlw2E3HBa',
            ],
            'the_tokyo_station_hotel' => [
                'room_1' => '1ra0HWttPWEY836U1QB-T2JmbDIy7_HRF',
                'room_2' => '153uHBjB8il4n5-7dD7L80NrXU37go8Fp',
                'room_3' => '17PBiSd5-jI5lDWBXIbXeIiN5N2i19-OY',
                'room_4' => '1vnBbTJ3_iZEHw0Z5hComGZq5QRyk_5QW',
                'room_5' => '1BQRxysFUkMyNW4HsotYkzJYqGRWWkJ57',
            ],
            'the_ritz_carlton_tokyo' => [
                'room_1' => '1s6UP4f0hnUJQWwOL56_nvgAyTTpXmvfy',
                'room_2' => '1oQ68vp7tPICPXGnR1Sow8Z5WHSm99x2P',
                'room_3' => '1H__htAEOHxiAM-FxluwM8r_xc9AUXZjy',
                'room_4' => '1poahH1z7rHMmsWp9zrU5QIETKDQB4TcJ',
                'room_5' => '1WuBG8PXUTKBhIu1QgkobR4LS6yS7BTF-',
            ],
        ],
        'mexico' => [
            'belmond_casa_de_sierra_nevada' => [
                'room_1' => '1rTwgBDe4y-px5ihn_muPGnB5uhiVybyv',
                'room_2' => '1NzJDyFtt3z5b3fguymJkE-iM_LlaIR5F',
                'room_3' => '1cO-l8cNdhnVF4nwQMIpa4ryqSNB9_ttB',
                'room_4' => '1WZbeJs2tqJ5AN7CEms2ndSTZGzzyN_Gu',
                'room_5' => '1bQ8_cdOdGta2bkt6BTq5iepguGaVlR5A',
            ],
            'banyan_tree_mayakoba' => [
                'room_1' => '1SlPBBtRgxuK5yXdrfk6JT7JuVqRSe0bl',
                'room_2' => '1TJOTsWMBcOyGoiYU1E5ja8rrtxJzskFN',
                'room_3' => '1xh51IQu4jt2jQUKVrkPnmWzka7h9-Xqw',
                'room_4' => '1QsZVzk-esXMTYGU7qIrtT2Hy-4DAWb21',
                'room_5' => '1xQW_usvI07ArvuWKzcP4RIGEbn9TnRaH',
            ],
            'grand_fiesta_americana_chapultepec' => [
                'room_1' => '1JNdQrT8PmC8Kg5sF3I3bl4llBSsjjwCR',
                'room_2' => '1wyRqax2U1Yxl32gpV5KyIzL7TmFlU11-',
                'room_3' => '17OE8Ox5GQM0elbE2DmqUEAnEqzJdsxId',
                'room_4' => '1FoiCd9moXwAJO70NJPYorkMEspmIYZVS',
                'room_5' => '1q38vZcsoSO1wqBrrgfC2I_k41kUHsw09',
            ],
            'four_seasons_hotel_mexico_city' => [
                'room_1' => '1-RSor_R51MXPpQ69PYVxpe8sUowex0_q',
                'room_2' => '15_Vbz62mxpFmnXjAVrB5IcY-LNofsBhz',
                'room_3' => '1lN4THl7wMxMXNojf_yYNn3pvgFs6q3Gq',
                'room_4' => '1WV8aGIyrN4DUNyK8SmnQLmWl4VwWbQzy',
                'room_5' => '1Y8PtIssRanvQILehouNUsUJaLNyOq3P7',
            ],
            'grand_velas_riviera_maya' => [
                'room_1' => '1qlepqIgwcKlw1j_GKJUPG_QzBMVDfp3H',
                'room_2' => '1fLFm6QT1ec6lr6L99TIubFZDmeImU7DT',
                'room_3' => '1gDXYO7ACd-NvAF8l46TFUEb86f2jjq_H',
                'room_4' => '1ZubYPT4rVs3l2Nz6dYqhho-rR1VRRhRd',
                'room_5' => '1tUHIonvJogMpcjOySpFOQoUWSIe30Pdw',
            ],
            'hotel_presidente_intercontinental' => [
                'room_1' => '17qm1dan80VlCbhw2pb8nvC5SG0oMBOCc',
                'room_2' => '1BAvjlTx8fdCLGat2lkSSPMHWDb86Szqx',
                'room_3' => '1Li0nYYBcsRQhbxusrxrsdDU_Faegg3Bm',
                'room_4' => '1ue6IhMXKP7Kbs6KVa3ngUFzCC0jNLWWV',
                'room_5' => '1w5cF_DLHyN0djINAssJ-shdKPEIBOcCT',
            ],
            'jw_marriott_hotel_mexico_city' => [
                'room_1' => '1CbYBT4fbtruahKb8c14vMvUBW-_Cm8Pg',
                'room_2' => '1BFw0SovpdDPrNQR0iXkVGeOuE3Wfv4cG',
                'room_3' => '1aedkAo0JA82BWiWX7II3GVUItptkw-Og',
                'room_4' => '1UNklVAZ-AJ_4rZDR7yA-zo2RWrIh2MWv',
                'room_5' => '1_4WRdKHv4UwDhX4irJL60GH-PN938nol',
            ],
            'rosewood_mayakoba' => [
                'room_1' => '1sFKqQIoEOr6SUBkHwj1fGn_PKMGPEvAp',
                'room_2' => '1aSuTIvRsHERGWQsuQLjSQB5He-Z2gDbV',
                'room_3' => '1mzj3-ELNuN3FX-SoQ7dy6Gu_eTsYq1lV',
                'room_4' => '1W_1iYwdh2g2ZiNwrGlVFWQOABPMqvfe3',
                'room_5' => '1MNL8bp2ns2k3E3S47es9vcM4-UqzdZ5L',
            ],
            'rosewood_san_miguel_de_allende' => [
                'room_1' => '1r7GtrzZU8FB8TP892PcChYLpGGP0ZKrf',
                'room_2' => '1UHzVb2K3OqCsoy74a8U5yQQV01yroUm8',
                'room_3' => '1NvV2L6UB8aOLIq6G-z4BjPxmudPV398b',
                'room_4' => '12UHRs-YWzsk5moNi9GKJWaEOVhL5vU5A',
                'room_5' => '11lEsxX_kWqhcXVTdoXPAQ04iIDm8ALP-',
            ],
            'the_st_regis_mexico_city' => [
                'room_1' => '1y2Q-Kis246uvyvvVHB0WGVnds9rvjgiL',
                'room_2' => '10KLuV6qwtn0tuaEoU0Pc5X6O-JFRFgFy',
                'room_3' => '14zDYbLWmwBKAURwawuODcHnz8IcKYW9P',
                'room_4' => '1cWasBcELOlktSDMYtjt_23p637B7e1iC',
                'room_5' => '1WT5HGEsofpXRqEOe_3JaHvF27Z0_15Lk',
            ],
        ],
        'norway' => [
            'clarion_hotel_the_hub' => [
                'room_1' => '1vTOmVXF2XQLHJ_YVGt7FeeCjUoO_pRTl',
                'room_2' => '1D_V6MBoudfsGFG8hkfC4raiK2qdTE5Ua',
                'room_3' => '1O1cieeU3wxs7fc9v1v9HZIl3XJaFc0_O',
                'room_4' => '18vXfkY1rcpiGRXtc0HaX9xi55G4XIfh9',
                'room_5' => '1vdvTkZaHpDUrq-QycJAy6bHzCCSfg2r4',
            ],
            'hotel_continental_oslo' => [
                'room_1' => '1pRL3Bz-ELSWP0dUdUOY2tHNhrgEWfMQS',
                'room_2' => '12OzGjvZrmqnLj-u-qo-CzIrMz6buSj4c',
                'room_3' => '10LXzrWtK2-ZUw8VNAEb7lZaEB87tapKN',
                'room_4' => '1YvgZwsTN9DYSac5C9ntPr9Jcl0_MGzLw',
                'room_5' => '1AzM6CmeuozvPF_ALhYB1eQbAWfnV355_',
            ],
            'amerikalinjen_oslo' => [
                'room_1' => '1_pk89gC9zCGGxVRj3fK559MkrQrzRgMA',
                'room_2' => '1dqGlVoR14yFWVzLEIDzkPU1aof5cRgnL',
                'room_3' => '1qbIUeq7UqG95_YXu-vXf5EqcWmyA5zHF',
                'room_4' => '1I1MaUgHjN1w4QBfj8BQG4LoDALgooBAt',
                'room_5' => '1Z5Wxel91IRuq_R9O2SJv_qxPrOjBmGCk',
            ],
            'radisson_blu_plaza_hotel_oslo' => [
                'room_1' => '19VG-0rDrg25Q64t_Hv3-T9y32_i3rYAh',
                'room_2' => '1F_LIY3WYO3yiXZv53Zw_BGXa76R1wUiC',
                'room_3' => '1IsqFOmnK_URuy_pZUbxRUNilAdfS7ykv',
                'room_4' => '1u6glhqPixxjG3dvAzm1hgelQicfGdFCM',
                'room_5' => '1OlZ8cJz2IqoZ81w4-tFqtozXQv7fsEeU',
            ],
            'grand_hotel_oslo' => [
                'room_1' => '1lY6UX_sSOT8F7UPkO-d4MlXmjpX3xa9v',
                'room_2' => '1t0YMp6a70auG7eBdgxdXkyiD_uRVxB7t',
                'room_3' => '19sVgY9mMoKasWHo1Vrngj8QWJeX8lotu',
                'room_4' => '1Ufo0Q7udHMYa6DNwtEGrgwUP5B1XIzJZ',
                'room_5' => '1ecG7RQgzhZqiXK2phDszzC_ZlSRWiZuj',
            ],
            'hotel_bristol_oslo' => [
                'room_1' => '1GhEneDnp4yZJvgG1-e-fMrsHI5SFhCH_',
                'room_2' => '1Dvw0TIXiE2b3NI7yGMgYWDA8A7UMIW9J',
                'room_3' => '1R9md6K3fvSdwL_ciL0Ik6IOxLSreY3Vm',
                'room_4' => '1u9W2y12njaHK3rCxrSIshZckawnK2pM_',
                'room_5' => '12T0pFM9UL5EDLg-z_KoPjZGxSGHJiYyi',
            ],
            'scandic_vulkan' => [
                'room_1' => '1EgUjVDNi5a76KPivJ8CkXWTbVxcY4rPf',
                'room_2' => '17zjUv7AE8sMJrdOG6zGPTO9d646tnnMp',
                'room_3' => '1HaSkAFQtstCR15Uj-xTsiJQ0OXtj-mMy',
                'room_4' => '1rpEI7l9CzxyMOqDK1upCO68dplFZJCth',
                'room_5' => '1Nz6NwnN5EcRUvzwGzPZ0PtOQB9-y6tia',
            ],
            'scandic_holmenkollen_park' => [
                'room_1' => '1i8WOQyl0zFe4gLnOroMHzhZi-URpM5LY',
                'room_2' => '14ErJm1pHBmTXOsEXSOGX1OAVMR-QSbNr',
                'room_3' => '17kxO_Seu_Inzm7OXfjAxNIhraqUptwAa',
                'room_4' => '1Hq9FMehAjinz09uOi__3RcQr3htcnNd8',
                'room_5' => '1x3_DoaGNABsZC95GB5-aJTr_KzWdAWTO',
            ],
            'villa_frogner' => [
                'room_1' => '1YHatvhTi5qdnRplqQKvv_McYzWcTadkq',
                'room_2' => '1WEEtk5Mq_Sjf_IaShTaSFYZuRp6if3FK',
                'room_3' => '1tQ1G8q2qs2tAfWSngdSvAFUwjWrzALx0',
                'room_4' => '1tuGKStcho3l0SFjiIAARLjYYPcKGppN-',
                'room_5' => '1KaKqR06D3iceILvbSFbS6DkR1JZWpOoM',
            ],
            'the_thief_oslo' => [
                'room_1' => '1V0eFDlNCaIcLVzhpvnr2q4aOEIR1xZAD',
                'room_2' => '1lMg0n3nUeEKZ8nIR0JvXXp0N6VLQiLKl',
                'room_3' => '1hJ0-jo7f7O-6O0N0h5WpswoWZ476EsLg',
                'room_4' => '1F0Skh3taUHDuIvptQk31oErkx90m0wgr',
                'room_5' => '1VdD5OqVz_yLzjlUVM77fgPh0zq9cThrC',
            ],
        ],
        'russia' => [
            'ararat_park_hyatt_moscow' => [
                'room_1' => '1qXFvvpECggvv0DARNPs-HuVQYHw0Rnzr',
                'room_2' => '1XsLqkz3QAHfXgDBiFeEZE-oc87jEtsS_',
                'room_3' => '18dO0EY_2e5RNLvjGzIMykXkGoUGmjfGm',
                'room_4' => '1jcpOmeTxbVj1Gu9PK863po3_rfZDWCy2',
                'room_5' => '1iJqDajXOMj75V8N95jd6SPVNHy0477kP',
            ],
            'baltschug_kempinski_moscow' => [
                'room_1' => '1tq_Apj9HX9OTQVCDtNCsB_yZHx1CjQv7',
                'room_2' => '1VuM1PKwb28ywFbMINPsmyhI2CluXeCJf',
                'room_3' => '1xuvcXufLkna4O7lkq4rJOTLTAwAHeur2',
                'room_4' => '1Eb7Ogga-0DaQuiTJsB__3hWH8j-fyKCU',
                'room_5' => '1aAmlpOWZBjqyo7a2W7VaaoA-uvIMPcWb',
            ],
            'four_seasons_hotel_moscow' => [
                'room_1' => '1f-NmCvZDBnrAIp0FdJlB437WfxCpm8HJ',
                'room_2' => '1WHF5LAY3UlYpodKVl3x-xpGSNXfXhU7E',
                'room_3' => '18IhbLM8sFzm2P8HfVMAaQsdzp52SRHoX',
                'room_4' => '1l-4AQjKiy5dO3fpi1vr0R6nwHfYD-zpm',
                'room_5' => '1IfbskX-B5qiuZuYy8A425ive7vHS4BD9',
            ],
            'hotel_metropol_moscow' => [
                'room_1' => '1HGk_hVBtyl8j4Ydqkn7R4CAop4Bgdoot',
                'room_2' => '1v-ApggoG3NuctoGWwLpgNbxzhmgPLb-i',
                'room_3' => '1zFz29v4JbV3-DOya0l5xx6Vu-PYvrHcY',
                'room_4' => '16RhtDHSf51wfvGud8z9N_Mk-UKQVXAAl',
                'room_5' => '1DiFzNfEPdNWibfviI-RISN_Iqu2bIHw7',
            ],
            'hotel_national_moscow' => [
                'room_1' => '1w12fgUDME5mB-107_T_gwae0vnWmPSuO',
                'room_2' => '15HKwQtfF4QOpM3HU4x-ap6c6dh5E-vjy',
                'room_3' => '1Jhs_Dsbn8EuusOdIahmYXGC7WkeDCqeL',
                'room_4' => '1BHrr10MKIf7WwBzHoTkDmeRvi5dawMcO',
                'room_5' => '1mVq4lGS-Fk8nttPhX8eowqczAghebXVz',
            ],
            'lotte_hotel_moscow' => [
                'room_1' => '1_orfyQczUL3vrDkn2n6Yv2v-iUVV-sJt',
                'room_2' => '1YMBkANKbnVAssLAEtg4X0q2DzxZjSXg-',
                'room_3' => '1nZdnHNcmMxXKIvcxxxjKfwHro_qL_Qhs',
                'room_4' => '1Vfq4FM9qgw63qD9AFII8yDrtWLJfrOKd',
                'room_5' => '1u0-fNlWBz0jTkazn5UlDM4cgDttArsop',
            ],
            'radisson_collection_hotel_moscow' => [
                'room_1' => '1pE0kOXhF79B1T6PL_ULn-8jLH4UoC5fz',
                'room_2' => '1YCFvGTzfx4c4jTWf8EDRcmZfy73GljsK',
                'room_3' => '10XpUS1zYt2UQWqYiJwAI65HWV2s4edrd',
                'room_4' => '1ft_qBkwzK-49E81Vw8KvbHCxvCa7PpBe',
                'room_5' => '1bpPZZpyKlYwrIUCr0V0au8ywDdxX_jr0',
            ],
            'swissotel_krasnye_holmy_moscow' => [
                'room_1' => '1OEqUnIydmrVvndoWLzZLRW232IGydX_O',
                'room_2' => '1fUsqQyyKIjIBA1XZyaqIXuqKUSyLscTw',
                'room_3' => '1MJF5tjVce92HjU_IjLIUcLJ2SDMquf4_',
                'room_4' => '1cHykGbStorhq5bpTqAGXEsBWikE8i8J5',
                'room_5' => '1ZQZYcYiHmO6OO9ArUZYydUXrYqtLLbhb',
            ],
            'the_ritz_carlton_moscow' => [
                'room_1' => '1oYD-n90_GtKN2efbYa1wT-0bIdONlvWu',
                'room_2' => '1K9yoIPURH78T-JmF6K6ed5oxePamnH0T',
                'room_3' => '14VnVXcPhO_EC4vbFIMO9_IagseWZM_QC',
                'room_4' => '1K1ho-qMWsx2q4JYSr-XKw5Cl_DMUw-d7',
                'room_5' => '1D1AH1dMN-3R-RgGAvbA3eBSweSFS8EkI',
            ],
            'the_st_regis_moscow' => [
                'room_1' => '1LEzTZ1RdPrs5i9EvDiSjB4LfjXhXbgTn',
                'room_2' => '1nl5h7ERzR4A2k2EpNGiX2YAMt9KMSYEU',
                'room_3' => '1AoK3DA1N3khUpPMZMpDzYDSu8NhAi0s8',
                'room_4' => '1MMZQOm7Ypu-aS7Il4VIlaUQs2H0_jsLS',
                'room_5' => '1npV4BMVzqlTA4wHbvz78TKqHGHxELe-y',
            ],
        ],
        'singapore' => [
            'park_hyatt_singapore' => [
                'room_1' => '1HuGgfqLL2tf3Z8j-RvtIQQnSJn32GUAT',
                'room_2' => '1DLAmarD_I1kPWv31y1jO7W2xr3SxGDUZ',
                'room_3' => '1fM-tM44Jjy2wplKXRyrrRfGIl3CLeW8E',
                'room_4' => '1CR7M37_wEFLxRWtupoJJjF1GKufUHBbi',
                'room_5' => '1j5sa8zcabHL8rOsOifvJQXpbT51_1809',
            ],
            'capella_singapore' => [
                'room_1' => '18u1k_frMfBZHQa9mojg6e-v4zZaqiBmh',
                'room_2' => '1qsT4kmYaBuxmVpAtRXKdzC9rmnsiSCCg',
                'room_3' => '1BOxbLdyQ5yMjrpSoenBMPGQR5g5CKNyo',
                'room_4' => '1W2gqtEB3b3z5uQqW4HUW60cqvucpv8rc',
                'room_5' => '1OW1hiIQBTO95t2ExzgqJ4N_sVfnL8p-O',
            ],
            'four_seasons_hotel_singapore' => [
                'room_1' => '1SGR4gkdEwjGJAMsq_fQPsV4b0gJ8ub7S',
                'room_2' => '1tBhjTugXv8CgCQWH1v94o5IuO5oYNorz',
                'room_3' => '1Uk2gGzItwDyNLDqmMEL14z0-zyltUhuL',
                'room_4' => '1ZkbCJcEeJvcLUE7UjoAIQsMCowlT7Scf',
                'room_5' => '1hWYiI_2PqjMWO2fYnETQ51MEKtXv7z3q',
            ],
            'conrad_centennial_singapore' => [
                'room_1' => '1n6fKY2Na4kx-L2UqmMY0MjjV7mT_Ait0',
                'room_2' => '1bkzkpQfYAD_nPJBjwyniiBB5PVgq4QMl',
                'room_3' => '1qq3dpdWrcgpK7dEbDUj9UXCjG9Uzw7ZN',
                'room_4' => '1HE8H1whaZwKxxYV2VA3SP7Ruw4h2NQ0D',
                'room_5' => '1T1uwHA1EaubNy1WuQgSVRY8tqzOkSJ33',
            ],
            'raffles_hotel_singapore' => [
                'room_1' => '1RDZ1-xNZzRJEXB3OgfTvLFqbRSGjgeMz',
                'room_2' => '1ikORjWD_7tjHYWl0yPlAS3dXFNxj_gSM',
                'room_3' => '1iQDNAQUB3uXIHv9pr5BDutysyDTctaRd',
                'room_4' => '1P_1WFpyLiMovm1FBK9Wc_Lc1ImfMuwEP',
                'room_5' => '1GTKA6cHy9omspBG2yMPB71JzDKXlu7CI',
            ],
            'marina_bay_sands' => [
                'room_1' => '1LxP1uTwOnH5qaG0bHS9kUpiCEhs28mXs',
                'room_2' => '1yJR-2gnN99xCrCBg79eOLSbwq1ENFbG7',
                'room_3' => '1KyrMwBGE1xM45OrQQLqr5LF-KzYFVvFb',
                'room_4' => '1fmqBQ3TOJm4wAenTs4s3bXEQMYdP_7Vt',
                'room_5' => '1R74PnQfRlfc5SUuTATyiUnIU7W7llV_f',
            ],
            'mandarin_oriental_singapore' => [
                'room_1' => '15MJyK0BX8Iwqe1RZtYZvpd2ss9e0oCMM',
                'room_2' => '1DCm948jDz7_dboNFbKYNSIRPym_qc-zs',
                'room_3' => '1zBXWQpJKfZWu3BL_T0Tc6nYFb4gvvOG6',
                'room_4' => '1kF5jpmT3m2nZ5OwkOahJq7Tp5Z8dYPHn',
                'room_5' => '1qr-pW6Oc-yGdsdkuOwaI-9HyDfnuPU32',
            ],
            'shangri_la_hotel_singapore' => [
                'room_1' => '18OWNHpc4tW74A1FINL81ifj--a575lCE',
                'room_2' => '1D-8S7HzRrdc656Eu_oeZ0c4fFNVoZhYu',
                'room_3' => '1IU7O8octMbbgianLm3EWuBRWdTQhzu-N',
                'room_4' => '1TRU3pNZLECGWN7nwc9_C1jP09u8kWZ_S',
                'room_5' => '1ceFf-oCzEZyfFMKRR_LBWbagoWJmeGRx',
            ],
            'the_st_regis_singapore' => [
                'room_1' => '13YZJo-HnwCpFQ1fK-K1cpnCecwP5f9Sc',
                'room_2' => '1seQrxqp9STZTSPPtsoBeMHzgIPktq5kh',
                'room_3' => '1MSB7xwP42cH-bonhQwrfA7awdwDM8mCu',
                'room_4' => '1O317dYzrERq3m_oZnVed4ES2EHT3jL9k',
                'room_5' => '1FBaUPdEo2ODmJi64OC8l-TWvothrOe35',
            ],
            'the_ritz_carlton_millenia_singapore' => [
                'room_1' => '10v8-Y-M1rbFExcyXwgPJruuj74S__j4N',
                'room_2' => '1V4oTIHmsgfpPtv0nhxs8MlZKKw61oSdW',
                'room_3' => '19ZMNLlRmyNCbWUgLFAF-u8Y2aIQcCLNS',
                'room_4' => '1ghtWad4Vxu54aYzgw40CRyHWnOdltBjP',
                'room_5' => '1WA7YzHcXSPVtx8bGzkdBL8CrUPIQkvr5',
            ],
        ],
        'south_korea' => [
            'banyan_tree_club_and_spa_seoul' => [
                'room_1' => '11uzmIVDaAlQ51oDjx0H4w-P0nqoSpOT9',
                'room_2' => '1D2ltvPYFNWRJAKR6ebeRypTwz6V0WR5o',
                'room_3' => '1ze6vfWPyzHT6VsQbnvOZUUcGP2Gz3EDD',
                'room_4' => '1UsY5wG80DHPG5ubPQ4gCX45TUbVWw3WM',
                'room_5' => '1Ii5yqBfnkuggk2PJu1f7eABL2cZbnw_T',
            ],
            'grand_hyatt_seoul' => [
                'room_1' => '1DXYfn8SYPcUovX8LxBxoPDMmKnhIPBBj',
                'room_2' => '1TnNoJQH80vHVVbgUuLTdx-sGoBgA4HJI',
                'room_3' => '1N19NiK8Olc_Wc3jmJ6XM7EDMojLLqqdG',
                'room_4' => '1SFkRK1AZ_CB_O3L7bwAVTGP5nIRqN9m6',
                'room_5' => '1eGGNQ_pRw0YeoHjdevIzNNCxGQ0VjdOk',
            ],
            'four_seasons_hotel_seoul' => [
                'room_1' => '1FnLfuxPPF8w2dz6VDk5AjopP2A6wBx8n',
                'room_2' => '11-U7X2pEa5w_EEXrpoH0_7M3Hwl3Sc-V',
                'room_3' => '1eVS-AnRvl0RF-2I87Bs21ba4_nQd7QKp',
                'room_4' => '1CkmtmiP2LrwH6Tu0XJsZqKC4Cf6i4kRe',
                'room_5' => '15mHNQpEeGqKu8bncrFx7MoZ66EGmTV6p',
            ],
            'jw_marriott_hotel_seoul' => [
                'room_1' => '1lZqy6aMX3p8ngOpe3II1Us3A9j-2xTi-',
                'room_2' => '1jPoHpOQ1jbqt6aXt_RZFEZhpshqxWV3u',
                'room_3' => '1gyKk9plSx-yTFo7jePEZ6tOXvtGY1VHH',
                'room_4' => '1a6p41JCxpYpTMpkDGIBugj_UapA5aAhu',
                'room_5' => '1PMtcS2T78LzVBrmBW9iSrDaVsHrVDfaz',
            ],
            'lotte_hotel_seoul' => [
                'room_1' => '1b2i8CIJdqGincTXn3vxSWIdPB9vMG15Q',
                'room_2' => '1NZN5ykiyavvnbCHHsMXpXgyRU4LW44Fz',
                'room_3' => '1659xRnPHB2yw1Fg3H_qB641aSvsRztMm',
                'room_4' => '1eKe-E3LOUnwyDZCU1l306sUg8HRwO1yd',
                'room_5' => '1h1Oj2O-pvRhEhK-C4y1L67KI3-atxJCM',
            ],
            'conrad_seoul' => [
                'room_1' => '1nf2FXE6b5mmsRFnFMTqbUmxisZ4RLIs5',
                'room_2' => '1eczvbsmNhGT6t6VgI0-a-ViJx2OhkjeC',
                'room_3' => '1YV4aPZ0c3nGQPW4KaoVtb6T-6Azp5UMc',
                'room_4' => '19xGK-YH_pA43fMJXW50qk3x_UsuThrdl',
                'room_5' => '15fuzm4O_o_UqoDF4XtutiRQYmfSgCi_R',
            ],
            'park_hyatt_seoul' => [
                'room_1' => '1UpvA9LdAuDNzwiaYzLkrOZhI5QPmzMKB',
                'room_2' => '1qLZiOLkKXCGPvIrn7jmXaENMfkfPluEa',
                'room_3' => '1nvCyvXss5lfnjvCFpg1rExCtCzbYA058',
                'room_4' => '1CHjB5FESB9g9VYoVmQQskA0S-1Cwqdqx',
                'room_5' => '1SphFr5Oxt-DGF1HWOn9tBBecvme63xQ9',
            ],
            'signiel_seoul' => [
                'room_1' => '1uEf2oJhO5zDcuvqNdzd-PP0xU-RNtRjX',
                'room_2' => '13aj9KZsqQ0RVdHYTDBm0K9MedNIoZjPL',
                'room_3' => '1p7tBY9VKbdMffZa5hI9m1QXVsYAcPay0',
                'room_4' => '18ef-lfHtAjnNBWCGamdHnAPNDp0PGKES',
                'room_5' => '11kn6DmRLTNLtvzPB-c2yv22LDEtiLU7N',
            ],
            'the_shilla_seoul' => [
                'room_1' => '1764lL7HhqBx48GTnONTUXh_7eJDNRNrY',
                'room_2' => '18QwW4ShPg93YparHLir-gWaPqd1TPZo6',
                'room_3' => '1B3UctVKnGNSYXiy2maEtfLPVMKNWY3Hg',
                'room_4' => '13uqSPEQ0vm_D0p9rzxjqK54eWcNMz3dV',
                'room_5' => '14wipttM-qCw-We0DFqxiKdes_B2a1nW3',
            ],
            'the_westin_chosun_seoul' => [
                'room_1' => '14SlrT4MJhzAMqobjtaAzTP5YsFWHMb8l',
                'room_2' => '1YUTDWR0GJySgm8rSXsmCPWsJAsnQj6s6',
                'room_3' => '1V83FFQ9vIU6ITKtJcxTHD1LNEsOUaZrJ',
                'room_4' => '1o96Ik_g83YdaQaYjn7EinpalZAHKtCNU',
                'room_5' => '1-HtIiVpFmNGm5jahb_t2X6OyGRTbYjWJ',
            ],
        ],
        'usa' => [
            'the_carlyle_new_york' => [
                'room_1' => '1GX2fnLfqB9alXKHMik5M2BYkm1UTmlB_',
                'room_2' => '1QOaRngqLvyuEPvlbwKIFnLRsI-VXBCZL',
                'room_3' => '1MArwDWohug5-TG4Vk59Prmej6m4o9xGs',
                'room_4' => '1V-HGBSBrzHZ6d69BARSkI03m3V1GTfRb',
                'room_5' => '1YaQ2kybJFuadw6DPrTM1V2W0ZdPeiXIK',
            ],
            'the_greenwich_hotel' => [
                'room_1' => '1AoqJuBSsZHn6xBWzzZSqxIu6N3QFRy_y',
                'room_2' => '19lOtUjm6Zlhnat70_iS1YeMbFMCYD2tj',
                'room_3' => '1zleqaqJtWAJpII9xuxKy2xY7jkg-2tyx',
                'room_4' => '1e8yILMUlYDb24jf8PjYK45Txl_GX_V4s',
                'room_5' => '1kp5NCeYHFv22xYo7YhNMEL6kBp9p6cYb',
            ],
            'four_seasons_hotel_new_york' => [
                'room_1' => '1migavOuZj7jBUoU0yzZ8GxyffwKu7Dsb',
                'room_2' => '1wCShn9WUnmv86MuIs2y6CZXGd2TzfuaR',
                'room_3' => '1CLY40_oqqHaYUizNWO4NE6BwO_WYF124',
                'room_4' => '1y5v2zpb_wvJAL66JE_SaaOqLBp_4I_AT',
                'room_5' => '1UjwLx8jLots-EwmCSaLuHH_Mf4mIMlzE',
            ],
            'the_lowell_new_york' => [
                'room_1' => '1zDPLc6ImlIj1lccsTJUjzFanojEZ3lAh',
                'room_2' => '1cfi9FgdIOEymPI4DhCvJ0Z6mFi-49JNY',
                'room_3' => '1hlAucoYAfjXqyl3olbPfKWGVMlYvAGZB',
                'room_4' => '1FdzlKH23v3RXWGYR3EGMCbuVtZ5i2yn2',
                'room_5' => '1iLi5wTUsUm2KlU9YYXNNjIHtgnCTtvJ0',
            ],
            'the_pierre_new_york' => [
                'room_1' => '1jR69MqDNgbv-Fpk0Syt6iotj55KjViRp',
                'room_2' => '1cfb6VhVPqWUbaGpKahM0Y9wT9MVtdnnR',
                'room_3' => '1GygrIevho609xqo8JBUF8E-1QwRbjbdj',
                'room_4' => '1T0ePQvEBl3-ugqyR2llGEHjerDbOGSUt',
                'room_5' => '1YnrbmzRdeIQiT2bgetkq3XrVmfz2_WgV',
            ],
            'the_mark_new_york' => [
                'room_1' => '1xeyiO4y8O_Ckw0MfesSzBK1jP898d5nC',
                'room_2' => '110pKROxJ8p34k5olLf81PwZBmLwnybev',
                'room_3' => '1VO9opdJd_MGCLeNGa61aEn2U_R3dhaeX',
                'room_4' => '1NbmWiTkUwA-cFoqgRw_5G0osHM7y28j7',
                'room_5' => '1MzeGq8BHYKwDXFAgMhXT8PphYRu-kS5D',
            ],
            'the_plaza_new_york' => [
                'room_1' => '1nMD0KYcRtZMq4b-jt73MFn868eKRoWcJ',
                'room_2' => '1aYLMc7AIWYyGWv9vbs0L-U98GH_IZX6g',
                'room_3' => '1bMecanldO3mRZ_qAThwksgt-rrG9WDsu',
                'room_4' => '1p7i20ZBd5HfOBMlBAz-4pI9x4oPyfF0U',
                'room_5' => '1aJjxAxaXbv5-1-6kR5QcRCG6sOd7YlOY',
            ],
            'the_ritz_carlton_new_york' => [
                'room_1' => '1lN-V0Y_sQN1dXSzrHCJp4LoryGB7_ygr',
                'room_2' => '1khorIqbS9d6fc51dnMcwX_T8Ozipcztm',
                'room_3' => '1BnUJfrw2fz2YUiukD4DlOjMZFTjc0rpA',
                'room_4' => '1lC8kSi7VTgf5Hb4_g_lF0ZgzdA2ViZqy',
                'room_5' => '1X4-gXdALOmxSBoaBOCLMCXD_snPBdXub',
            ],
            'the_sherry_netherland' => [
                'room_1' => '1H6nXnYoXd2nzjIHefoVLEEOVGrb9f0hy',
                'room_2' => '1BVf-ZImSiNAhx34mc5JyOsOancoYdgUv',
                'room_3' => '13SHlwHWy_qHkieGplkzjnkzkjnqzhqaB',
                'room_4' => '1Nhvot7eaBulDAYH-uEZG21zpSMZCgF7Z',
                'room_5' => '1yVpvONzlW0_owzQEeec0GUNBG2rA9V-X',
            ],
            'the_st_regis_new_york' => [
                'room_1' => '16p6YeXq5ok__viqs1MjP3LKcxV4pbzOM',
                'room_2' => '1vXERAvIEkcdobdsnNnDzDmyPHwYySW9y',
                'room_3' => '1nQNF_gH1QK6aTF8WJSMSxYB4LRqD1wlw',
                'room_4' => '1Ds6pUz1t28WaeV5jMLO0LdyT44sa9VV8',
                'room_5' => '1Qe-WwtTrTRHpbVekNh1d6uq9801q35nv',
            ],
        ],
        'spain' => [
            'four_seasons_hotel_madrid' => [
                'room_1' => '1hSISDr7uIcjl1uWQoVwwdV571OBSmJ35',
                'room_2' => '18nCl8zWSzQQsvQTAa6XiJ2a2bEcchAcC',
                'room_3' => '1vvFD55JvYVtI5v2gaS6-sj6WqO09jZC_',
                'room_4' => '1nIHRvt914Ipzy6enaNz9fvANuNWcD86c',
                'room_5' => '1WYOupAxEmzSnoFwc58Gema-nOAbPOvE9',
            ],
            'gran_hotel_la_florida_barcelona' => [
                'room_1' => '1121Vk20EpC2mVhNrVJTm8IstmiyyqBs1',
                'room_2' => '14e72Rw6BvahPdqfhExVzrY-4d0t3m9vL',
                'room_3' => '1RiFussW9cOgYjJhiXgU0YwfwexNWcsTI',
                'room_4' => '1O3dyVJVJtm3aDa09l2ebRQuoy_oPgZAn',
                'room_5' => '1tu-AD91SeobCQralu5hqcZo8r4uXb_-m',
            ],
            'hotel_alfonso_xiii_seville' => [
                'room_1' => '1kO-8obqGRafu5psnkxZwiiwx88m358DL',
                'room_2' => '1l0mbKL7D0I4xGmeBnKQ-eZTcMWXK8re1',
                'room_3' => '11_GXYLuiquqih6ZBfFdJeFQnS2cyBRUN',
                'room_4' => '1J3Jra6dVKaNJZndNj1P1bxcCrYTHsPu0',
                'room_5' => '1z48F0r9MeGxpPzLTjxhviC0YDli6nE3A',
            ],
            'hospes_palacio_del_bailio_cordoba' => [
                'room_1' => '11cR0KktaBES85NQYb3XfEpVHpkN_oqsV',
                'room_2' => '1e02y7bcope2gciVUnHAZN1bijOKxIwnY',
                'room_3' => '1YUONWgxluegnrX-uI8XqCJ7Gr6Lb1UIR',
                'room_4' => '1TYA1DQEKYHY7iZGqksrJNgpR6j372cph',
                'room_5' => '1ycFTnyl6hK-Bh8sl67OtZ3Q7-I02SowX',
            ],
            'hotel_arts_barcelona' => [
                'room_1' => '1V433kmImlq406xqu-cVXP2FlOYQ1ki4F',
                'room_2' => '1Wz31V034UAp3j3hD4e_V-skkCCpombzw',
                'room_3' => '1UzaA16ldkL69rv1YyPU4GnOntihoqCy_',
                'room_4' => '11_cOsZnWtfhUQnNBDE9KFqFswZFvQ74T',
                'room_5' => '1L99RWigoMvW8dE8m3_CmtaFpi978L927',
            ],
            'hotel_casa_fuster_barcelona' => [
                'room_1' => '1WsjFdD4iFtJPbFOeIWoiZYN5VO9YdSQX',
                'room_2' => '1yOH2Aig45h8E0SpZKSaHeWpqCc4ZWe5Y',
                'room_3' => '1Js1wjsh3HYc-eV4ySm0vHWlDc1roiFEm',
                'room_4' => '1183BsuznyXqYkfEyXG9a4yXnrX2zZd7H',
                'room_5' => '1DUA4Ylhn_WkRzfhjJOnim-ZgypDTscJC',
            ],
            'hotel_maria_cristina_san_sebastian' => [
                'room_1' => '1hhFApC-Y1BYdsImIY_J80yPZl7AW8GD-',
                'room_2' => '1mwr0dOYQQBTmJLAmKsmQI6U27g1_dWfe',
                'room_3' => '175-23uIagH1AI-d2QrB7IHCmERvPvykC',
                'room_4' => '1ZpcTj87SvJfN5PJGsRWrr1hgApp8dlIK',
                'room_5' => '1vhMal0UzrQCXMab1Tk-qzNSZbg4lwp-q',
            ],
            'hotel_villa_magna_madrid' => [
                'room_1' => '14dZb8Gr-3Fo0-mD74-OyLTwqpB_0itAp',
                'room_2' => '1B_dkJT8MXtwdlf9L36rOx3TFbG_kvtd2',
                'room_3' => '1T4QAkCudfEK8C84W4ZgORYIImDBAYRLB',
                'room_4' => '1ljGolLepLlU8QPWzfdlz_T0kN_pdNvXD',
                'room_5' => '1BB_bRO5VYJcVzXFBAeA_LLI3vY9rBbwG',
            ],
            'hotel_ritz_madrid' => [
                'room_1' => '1uGokS60z-K4inOARO_bhVw9T7m1IiwrK',
                'room_2' => '1wnM1QeWpSbqCTsr7BUYJTjhrcPKdl20S',
                'room_3' => '1HwKWMGHcc57VddjxsFg94d7hTteZ83AF',
                'room_4' => '1VIdJpIQXfyDBRT5FXkrl_hLliSoRlwU7',
                'room_5' => '1q_aiZ3hUPA8H6MNZNgWsZFvD8PHwgvI3',
            ],
            'parador_de_granada' => [
                'room_1' => '1gbauwJOcT5J16-SD6O2aJMwNgtvRPJlx',
                'room_2' => '1EzV0XOJOcWFTYLAif7UmJuwcFJF0gdft',
                'room_3' => '1oYJ0PnXF0WAALaYiEWUyzDq95stmM6-O',
                'room_4' => '1iNoWJrMztBLl8F9VdMMUcOM-BfBHekIJ',
                'room_5' => '1FxdCyMTE1EnLdnxCJJfCQkIlhHOTrbOp',
            ],
        ],
        'thailand' => [
            'amanpuri_phuket' => [
                'room_1' => '1HpCJUw2FPiaQGAwmTx259GJeofk_-Aru',
                'room_2' => '1nRHoizPq4z6y-uWK-YZ9-MrzUoXgXaNO',
                'room_3' => '1RVen6fJ6DKUI24ebQc0KgAj4yr63l_ls',
                'room_4' => '1XCtGkwiM7whR5xO5xukvnivqri52Ndyg',
                'room_5' => '1IQYqCRS2-9fUx00THTUQMFdx30WtZ20P',
            ],
            'anantara_golden_triangle' => [
                'room_1' => '1uouqgj8xtDiyi4xIminIMySfGpc5oOPp',
                'room_2' => '187JiEmToIr6AAKZe9D3zuXEMDk89usVQ',
                'room_3' => '1uPlSIkcN04KT1XXDCINaSR44352oShRo',
                'room_4' => '1PBAM1roj-HVGRvfrns3f-LERK8Ty-eO4',
                'room_5' => '1M-97BZbXNloERbGI_IIvnSDltMFnmWnO',
            ],
            'four_seasons_hotel_bangkok' => [
                'room_1' => '1VF5CrQK61DjPwbbsaXKBLMNSEWqLMyn7',
                'room_2' => '1Okotzaays68YjWyMfYGr6XCzixPVJDyl',
                'room_3' => '1chELfHmA6_FYBOMkSLs1N__7U6g-B4Na',
                'room_4' => '1ZJBcFwoEH1sFKf5bfLN67OvaUZFz18kW',
                'room_5' => '1pjtP657gfGNGLMMjzZ6jmRKsAovKYtr9',
            ],
            'four_seasons_resort_chiang_mai' => [
                'room_1' => '1As5-8efTeaq3emfwi_KwU8VEljdcuED3',
                'room_2' => '1uEjOeyAn79Dide1LPo-OiOvase3dkWQM',
                'room_3' => '1Fndx82_9pfVSrD-8PdrxSvcB25OnBWR1',
                'room_4' => '1GwFRueQwaytG4bAti8CLhSaU2O5x3_Kv',
                'room_5' => '1-R-mkzFcGLAlr7hAdXlP7AEevZupUmil',
            ],
            'park_hyatt_bangkok' => [
                'room_1' => '1awe-k_LJ-NnvGSWAhYIa332ehcFAPMBe',
                'room_2' => '1LUuqP6w5gAcaiw0f3efKlKiCEl7ohhSs',
                'room_3' => '1XICzGmG-6AIhdWiX9CAF3-kZrVYXTQFU',
                'room_4' => '1tlbWR6NeM2IWlVq1c1-9GF2HMIJkhbKd',
                'room_5' => '1gxWTaiMBpzcJUy_34B7XgMikH3Ptjfsi',
            ],
            'rosewood_bangkok' => [
                'room_1' => '1TsNyBGx2wL-oPoy9K-5IX7GAVLs_obX3',
                'room_2' => '1a8VohnLwpg2rcIPot2qKt09gwpQg1FhG',
                'room_3' => '1Ix_ByrHrwOObkaOV3zOqGBcjtVP7A1D3',
                'room_4' => '1qDFVTpGI0A3NMlCAni08JvNTz9O9HHW5',
                'room_5' => '1aOuvuQPmV6z0UbDyvpyHcgB6eS6kdAr3',
            ],
            'shangri_la_hotel_bangkok' => [
                'room_1' => '1WzHVaxFyJn1VDcJglqP_iRzrb8S6AXCw',
                'room_2' => '1KpC-PXI2P6SLOzaboVw2pzdxv_VsGvoD',
                'room_3' => '1QgpVT7F-q7HWXDlHSOatotIpX6MpEbrp',
                'room_4' => '1uGRxnkH18i9YGHBx8N-K6tdaCLmfR_U6',
                'room_5' => '1MFNGU6ilBUpI9bQA8MgHkPwRAfnXdJuL',
            ],
            'six_senses_yao_noi' => [
                'room_1' => '1tcoCi3g8dK4kgmO7hkGgUNIMsFC9ppAm',
                'room_2' => '1YWqwHF348W6YUuEizkmbiqafJCqrUgzd',
                'room_3' => '1sfYZxmnOyO2z1-aZTnAtWFJkhne0G-PY',
                'room_4' => '1bRNVPqDkkBejhShzwSKt7Q2x_sYPu-HI',
                'room_5' => '18NbtD-X8baD4F4pP7WGXOl1O8cTXRSK7',
            ],
            'the_oriental_bangkok' => [
                'room_1' => '1U88JXPHRM3xUa7x5zglf1Kc4b3RfRuuz',
                'room_2' => '1IFpbx8OfJv5PBmj7vOZHReA2pEnItTJ9',
                'room_3' => '1UIVBLo53kYeVFrSv8HFPIv7ffEhqDAQa',
                'room_4' => '1XZwJ8KBQA1DxbH4mBxqCV1odg9XpH6Lh',
                'room_5' => '1PoxAoujByK0ivKWam8qRDlE_dB-UDaQu',
            ],
            'the_st_regis_bangkok' => [
                'room_1' => '1ebGX8adXg0wXyIK6n1hccz49d_a-1JMc',
                'room_2' => '1mveGvClM5ht_6QYaJelPSlOlJge4QZFC',
                'room_3' => '1VIGgzsXzszrBebHVpjShkWMl6UisCMS7',
                'room_4' => '19cx_dGG5pjLIFrUJTkZpdTLWz_UvFU8d',
                'room_5' => '1YonKkW03PcaEa9ytKSQsUUtyh2yX6-WH',
            ],
        ],
        'turkey' => [
            'conrad_istanbul_bosphorus' => [
                'room_1' => '1NkNxByEjlHPmqUIP7ND1Uqm_sPO-_D1P',
                'room_2' => '1zaK8pR0kkGoRryCug01loU5IJs8u8Dhf',
                'room_3' => '1KLWauxdCXbWnoOyUShaYED5El-mKEh1d',
                'room_4' => '1dVFfVRyW1DUUEmV1_foif-JlC9kW1Z4R',
                'room_5' => '1aSR7tFYPjyyFR7EwGxlDf9RiHczjP1z0',
            ],
            'four_seasons_hotel_istanbul_at_sultanahmet' => [
                'room_1' => '1k_cgF3zL8d3IL6AppRv4VZFJKKf5Tyoq',
                'room_2' => '1FWHoMRQ6jSr0016UorOMM1EIj4fyeMMm',
                'room_3' => '1JcbZXVjYH7ATz0jXjDDhps5hRgzExGXP',
                'room_4' => '1Wf3080J34QR4dHynJ-5sx8hUobv2s8mD',
                'room_5' => '1Q2Bu85rfigZSwvtMMjPk1vnW8TqXRZpt',
            ],
            'mandarin_oriental_bodrum' => [
                'room_1' => '1mm6miX3W7-6SKaE3qCxe2q_WtXeg_GPE',
                'room_2' => '1mgxA4VL1o6rwsP217yXSUfaovpsvmUIy',
                'room_3' => '1LS9ULKeCkeerRIwiHzSaWOhHDvX97hvj',
                'room_4' => '1zrs9hyxrPRDy5WQqXq2ttx-fPywP8wp7',
                'room_5' => '1fU4NBul7oSrlYHwCkazh_XXD9oduNKJc',
            ],
            'park_hyatt_istanbul_macka_palas' => [
                'room_1' => '1WrHj9i9QLjLAzfA8XhQ6Ve80dJP7akn4',
                'room_2' => '1wltSWYSe9DEDR961T35I6vy3hFVv3bSI',
                'room_3' => '1gqozJbZJobe8qOA1F69Un5FUjya04nhg',
                'room_4' => '1dez2IeUOYAknh4ZsPdSAkH-LMxtyKGhn',
                'room_5' => '14WRq1J7nVnPDV5RlVwHm3TTa78A4qNi4',
            ],
            'shangri_la_bosphorus_istanbul' => [
                'room_1' => '1ML8TkN4SNk5kMrccObSt_PXCey48W85J',
                'room_2' => '1AK8JIlcKMO5Sl_WL5clBIVfsqs8xBvl9',
                'room_3' => '19C6DOk5cSssjAsKoO9keDiPI-AHf14La',
                'room_4' => '1ahz_yArEMeONMeBgV6110iliCbvYxLqX',
                'room_5' => '1-LJU5IBvIxALoBj7XumR_UvRRncAcz5m',
            ],
            'six_senses_kaplankaya' => [
                'room_1' => '1TSIhlmU6eNUKQdlThwE-m07vRQZXjEuF',
                'room_2' => '1ZLH_IOW-0aQ-WWjdjh1xf_pjgEbI92qV',
                'room_3' => '1HMZZIzZLVxvzMGFZomxi6ACrsU9FiyAg',
                'room_4' => '1Td69ftSOMUQHZSpIHJ7AB9WluCSqruYl',
                'room_5' => '1Sr-QWK7971MfbKkTeNMx0k8Escm-lj0_',
            ],
            'swissotel_the_bosphorus_istanbul' => [
                'room_1' => '1UIHRqWjrOpT0BQEa-GpBU-n56CaeHXC5',
                'room_2' => '1y_RLrsibEs6-v6CehHuC1bRjh0zWf0Yr',
                'room_3' => '1J18MPaWgn68jyDA5OW8VGnssltR5ysvE',
                'room_4' => '1oOz37cymVByIV6qj_Izpc215j-fHJPU3',
                'room_5' => '16fojChdDrQuiWuzucTJdiupXF5xdEyU-',
            ],
            'the_edition_bodrum' => [
                'room_1' => '1G4GXg5qqWPZ_uzVJjaHCZCohRR7CTZGr',
                'room_2' => '1SXiY8iIHXOBGyLtF_3qtiWYgi6p1k8ay',
                'room_3' => '1rpEWc3XwyNLGwAMTfNyVIb7O6KOPvzuo',
                'room_4' => '1M6hWAcIwkZGVdFBoy-Vkhi7Pjevw0mp-',
                'room_5' => '1AtPC_3H4KekLdVTJ3cTurO2c_7WtKRYA',
            ],
            'the_ritz_carlton_istanbul' => [
                'room_1' => '1FXx1B31C84FomT-SKiUZEp0rfl3ORuZg',
                'room_2' => '1Gs-2GLWoCISUxCgOzNHZkoYFBZaS3_IM',
                'room_3' => '1ZmbhzhJxMlQPVX_ydEp_kr1FP4LlLIq0',
                'room_4' => '1G9Ez0n6UPnEZHvIXMfMxjEASWbzoWNWI',
                'room_5' => '1k95tUNFSge_gBhS11JId99DDQN74s_Jp',
            ],
            'Çırağan_palace_kempinski_istanbul' => [
                'room_1' => '1IIMHa4I6riTzOtmo5ArXk9tuGAjVP1ou',
                'room_2' => '1t1VbcdL_qUQoY5F78kRTnGYo5o_-HDlt',
                'room_3' => '1MjnyW9PpZkBvTnsQcjECQwV7v407fQ7m',
                'room_4' => '1oQymWDnnu9IGfvz-odFMrXiWwI1yxxCk',
                'room_5' => '1s0P96mDIntHCreQQqtFyTytjQytLvuK3',
            ],
        ],
        'uae' => [
            'atlantis_the_palm' => [
                'room_1' => '1KHK7Q-inLjDYK63VJPUl-rKV9PB-AirZ',
                'room_2' => '1lwASrOg6B8o4BX9-A-ci7oURDbZjbIjq',
                'room_3' => '1ZTW62P5xikrpsOue2-eDCH6zIRJcC-6C',
                'room_4' => '1Erwj4pBr5Mn41a3LF9DD3hRvOAOYyMJs',
                'room_5' => '1cqJ_EP_RL70WN50ZE_XDdQahg6NqkcY6',
            ],
            'burj_al_arab_jumeirah' => [
                'room_1' => '1OsyNAvviFjtR5v7Mc54bRc3_vMK7FE1m',
                'room_2' => '1OUnrisKtHjzBZlWNGoeeNxRAKq3be_zI',
                'room_3' => '1DZ6NGWoBgCQBX38fFcyGKfbOvzK9MrVN',
                'room_4' => '1Mi4qE2PsYmJ7DtpDBcigI2K6L0hPhfWc',
                'room_5' => '1PXzpSsMIFZD8KMmVdAd1aYti42vJwi1F',
            ],
            'emirates_palace_abu_dhabi' => [
                'room_1' => '10AS-Jk2tq--aP7VburzPaCr_Ll4Qv2HQ',
                'room_2' => '15dJ-W5V65jiltF3nhAdOPwgNi7pJL3sc',
                'room_3' => '1-DWuW6C03r6bMqkCjWAiuya17-CBgQMx',
                'room_4' => '1yWPG9B-dlVSNKTIIgRUyUE937kYkMQug',
                'room_5' => '1DDRbvrmYSembxcN1ZSPt2RhhkrRFFhxA',
            ],
            'four_seasons_hotel_abu_dhabi' => [
                'room_1' => '1r4JAyocB3QAgUGm32zJf2suvZHNeTLWG',
                'room_2' => '1r3Bly1SLXk7YORidduMzqhXeMCDK1vXh',
                'room_3' => '14fuMU7iGZiIKJG7dJtkdgndaAxghj84I',
                'room_4' => '1ip-oX-VR2rpXtYMDJ-WSqndA08-YzW7N',
                'room_5' => '1Cyrpqf1xbtNFyTf-fI2xlH6Mc6D2KQ_R',
            ],
            'four_seasons_resort_dubai_at_jumeirah_beach' => [
                'room_1' => '1XptAJQWf2BZQvgDmwA8O05g5AuBvRe3e',
                'room_2' => '1NSLc15Oe4OgZtcBp2Dm7YIXIAgaxXq9c',
                'room_3' => '1QP-WHDIfPtkWa4TZUmzVvtr0ZYDVCjt0',
                'room_4' => '1gkuo0P-W0I3VHWsRd9GK5yUj_0xpTLDb',
                'room_5' => '1E4BlyK-Zq2M4dWCR_pb79OUYeg6obROW',
            ],
            'park_hyatt_dubai' => [
                'room_1' => '1RGfxyd5XWS7d-KEpvzuf2d-ctyw0aSje',
                'room_2' => '1H8Z2PeywU37vg8TNesECW-TMVi8TVOBd',
                'room_3' => '1-KFUfebM9cmjeWO5LLpXxvCxPRkIZWHA',
                'room_4' => '1AWimUTR8MRDdsfQiMmLbjPTz3RoUVL82',
                'room_5' => '1LGwexk0SoFdGjDJb-H2ZjaV7fcBpjroU',
            ],
            'rosewood_abu_dhabi' => [
                'room_1' => '1-tv0UIKDGogANsr4weU48z1SYzl9PRSr',
                'room_2' => '1JS3_8AvFfumb8WklFhaRxXOZDcBDg25t',
                'room_3' => '1mKrITqXHoxRIBPX3KbPlnhO9_sf6OuHf',
                'room_4' => '1HicOmRaCpM1iCDkahIASpUNwzUz0Tfv5',
                'room_5' => '1ODf17GjBJEBfd5mWxvu2wkKatEN4S36r',
            ],
            'shangri_la_hotel_qaryat_al_beri' => [
                'room_1' => '1G5cDnm4qz_BMQay33CGSGEwsF6ylf_XD',
                'room_2' => '1DJrtPQasDzJQonT5dN1gdcIq38ROZ0CG',
                'room_3' => '1tWEEFyWRZS8YqHXNEFeXJn0dvweDnYTB',
                'room_4' => '1VjR0jQrKwgadoAbgU4UdaLqNE2Vo7BpW',
                'room_5' => '1ID1pLwm63yHw93SEyOnQJWzyUCgF-1cj',
            ],
            'the_ritz_carlton_dubai' => [
                'room_1' => '1fl-sqetfbkil4M-CCHbX7s6wAG3IXZs_',
                'room_2' => '1uUyhI1-AsTtQoYdzY1Kz0DraUat6oUmI',
                'room_3' => '15n_ie35L7DZFNpnVbF3s_qxLdH6vscu6',
                'room_4' => '1ltzOjGjQ3HQ_8nHivc9aX9MHvY_JfEPE',
                'room_5' => '1xjT_f89wiK5Nb6CJLtilUJo1WuL9jMS1',
            ],
            'the_st_regis_abu_dhabi' => [
                'room_1' => '1v2h7qQcIFGg70SpqYq9_Rvnu6ozN001m',
                'room_2' => '1oNNkg6vDg-oio6wgPKY6RhJVMeZb8Nar',
                'room_3' => '1DYHPBcKsNy1s2gNBuQ1PMdM8imBs6Puv',
                'room_4' => '1AZIrpAZL_ob5EysYCR4JWTDxfAuFOR82',
                'room_5' => '1apC46_r7ydkJ7EqlgdNJcppabeyo1w94',
            ],
        ],
        'united_kingdom' => [
            'claridges_london' => [
                'room_1' => '10ou6hYlN0kpQ2sXCpaS7X_G6BM360dC8',
                'room_2' => '18tM5K04Pr5OCOTyrWcDcq6O5VwDYH5TU',
                'room_3' => '1slTav6MZqY69usNEklRi-wSy8bMIEufe',
                'room_4' => '17pg_M2AJnfs2d90YZsTGHSbTFSfT6bSD',
                'room_5' => '1DdQELtPUa1G9OPD1MDnRh3q2aJS5r1xv',
            ],
            'corinthia_hotel_london' => [
                'room_1' => '1pAaLrAWVk5A7ri10li0Yximz2TF37VxJ',
                'room_2' => '10C8wyBezCk7rPcPC45s2BLlckcWMmRdS',
                'room_3' => '1D8mmWxbUJz133yTopjaxVZrDXV19O1W7',
                'room_4' => '1uTzXalvy-UYpAFZmXvHUsvd8O9xNHifW',
                'room_5' => '1z4M28ARPMJepCb8Sc8GVf0K6PSRXa8b4',
            ],
            'rosewood_london' => [
                'room_1' => '1iFpQbEgPLhVLlaENb3tJ7VsCPtizKtZi',
                'room_2' => '17GWU_Gl8tE9_P3NOOBRR69CxxodJqTqP',
                'room_3' => '17E80mUydFne0oS2Jbjl-VP-z-NAkIe2D',
                'room_4' => '1GauqBTSnlPj_3UObFXoXWAFJbwFpQPVD',
                'room_5' => '11lBb6_Pg8cRkSdigi-DT7E_VILKxeF6z',
            ],
            'shangri_la_hotel_at_the_shard' => [
                'room_1' => '1BbCaMeQGcuZlo-IOEAkEynXrixmarAfj',
                'room_2' => '1_AsyGENBIO7JuzZ6anfmdCZS1ens187W',
                'room_3' => '1g0xLwS4nYLNpmZxTXvlvaRnQqOERRoFn',
                'room_4' => '1HAsFzl_LD2TzbYXrAGpMxfvR5-4mVf3B',
                'room_5' => '1ywo1lufgbdTVIm9pxCkaxLzgaf2BKwDc',
            ],
            'the_connaught_london' => [
                'room_1' => '1rDB0eQq8vnOYiYi5it4NbxuWwdH4u-v4',
                'room_2' => '1aD-j5TCXUXFJS574W8h-MaNCgDURCZ6q',
                'room_3' => '1R3J34_c1rrzu7hXs5GjmnNr9fku6YujK',
                'room_4' => '15YY2CYaEovnY6G0iPjZQ1QNlaEk5Th7e',
                'room_5' => '1biG7BSpD3qBBH2GSB72RT-wnCe_cDMJ9',
            ],
            'the_dorchester_london' => [
                'room_1' => '1hhH_G85vcJuNt4aSrxRC7tRPyl-mxNl4',
                'room_2' => '1sHKuGO2Qt7wE7mgCNMSPQR4_DlOIHk_h',
                'room_3' => '1d6_spSei0HpqZGXbbqTqQ9tYQM6FgkQ_',
                'room_4' => '1VVZqtBz1sUU8X4H01aNZJlknxODxW-U1',
                'room_5' => '1n89oAbfOucG2B10kGOfCTOZtVr75wAxg',
            ],
            'the_langham_london' => [
                'room_1' => '18imf_yfCRf47kIKx0DOvqOJMvo_tScpa',
                'room_2' => '1yvMWfOlgsT-qE0dEYzEC7DAwEXtHJH5G',
                'room_3' => '1jeHtDMaMAQEQol_gQy05POwswVXB2t9b',
                'room_4' => '1djOvGH1NFNuJuvshbQ2tgNploYZNvaFz',
                'room_5' => '1VlJ7MaSchn2P4ZIBhbTb1j2Ah6Rhmnv3',
            ],
            'the_ned_london' => [
                'room_1' => '1lzw1VA0yQlT2NM_uFW3fMHGGlJBCtzIy',
                'room_2' => '1OI3OjNkkc0q-PYe_LtHdkMUkCTiMEQhN',
                'room_3' => '1xoUWvYvwfTY0Q_PJUUE5tD7WvnChkSBS',
                'room_4' => '10V_MuDODUXCmaL51IWETpC-cjacRcvch',
                'room_5' => '12i8DQTfA40ckSEa3n_ThKcBNciD-ECop',
            ],
            'the_ritz_london' => [
                'room_1' => '1EE5-BmRoGQV1i3akzk1sw141B8zEeAL6',
                'room_2' => '1y784A8Va1oYlelAeY1D7N6HpkZX7_1AC',
                'room_3' => '18G5Ym4kGVSSgbgVgTyNoDGZsfNOFEUPs',
                'room_4' => '1ZKE4rYiMBtMmL85bs1ug9zIgqI1OKr8J',
                'room_5' => '15C2oGeJqKNZr8DBQuYBnfDPQ_P6c6UUG',
            ],
            'the_savoy_london' => [
                'room_1' => '1eZrD_JRuhtKioC6HnfKp5HVuvRjaL0Xv',
                'room_2' => '1E8tCFg4i-marW-2I0eVVmqfqZhbZF3DK',
                'room_3' => '1jjXbuselzTYYkQVZjQTzKuAMqiAgNlCT',
                'room_4' => '1RXJ6fZTjI3nIrcPjCsN7aGStAwXeHZ-S',
                'room_5' => '1OsZgptOGMXoiICcPvW5uI1KjwDzDTYgX',
            ],
        ],
    ],

    'fallback' => [
        'hotel' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        'room' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
];